
characters =[
    ["Cruella de Vil", "101 Dalmatians", "Fortnite"],
    ["Freddy Krueger", "A Nightmare on Elm Street", "Ready Player One", "Fortnite", "Dead By Daylight"],
    ["Alf", "ALF", "Ready Player One"],
    ["Min Min", "ARMS", "Super Smash Bros Ultimate"],
    ["Spring Man", "ARMS", "Super Smash Bros Ultimate"],
    ["Ribbon Girl", "ARMS", "Super Smash Bros Ultimate"],
    ["Twintelle", "ARMS", "Super Smash Bros Ultimate"],
    ["Ninjara", "ARMS", "Super Smash Bros Ultimate"],
    ["Master Mummy", "ARMS", "Super Smash Bros Ultimate"],
    ["Mechanica", "ARMS", "Super Smash Bros Ultimate"],
    ["Byte", "ARMS", "Super Smash Bros Ultimate"],
    ["Barq", "ARMS", "Super Smash Bros Ultimate"],
    ["Kid Cobra", "ARMS", "Super Smash Bros Ultimate"],
    ["Helix", "ARMS", "Super Smash Bros Ultimate"],
    ["Max Brass", "ARMS", "Super Smash Bros Ultimate"],
    ["Finn the Human", "Adventure Time", "Fortnite", "MultiVersus"],
    ["Fern", "Adventure Time", "MultiVersus"],
    ["Bannana Guard", "Adventure Time", "MultiVersus"],
    ["MBO", "Adventure Time", "MultiVersus"],
    ["Gunter", "Adventure Time", "MultiVersus"],
    ["Lady Rainicorn", "Adventure Time", "MultiVersus"],
    ["Snail", "Adventure Time", "MultiVersus"],
    ["Jake the Dog", "Adventure Time", "Fortnite", "MultiVersus"],
    ["Princess Bubblegum", "Adventure Time", "Fortnite"],
    ["Marceline", "Adventure Time", "Fortnite", "MultiVersus"],
    ["Peppermint Butler", "Adventure Time", "Fortnite"],
    ["Earl of Lemongrab", "Adventure Time", "Fortnite"],
    ["Ice King", "Adventure Time", "Fortnite"],
    ["Cake the Cat", "Adventure Time", "Fortnite", "MultiVersus"],
    ["Fionna the Human", "Adventure Time", "Fortnite"],
    ["Alan Wake", "Alan Wake", "Fortnite", "Dead By Daylight"],
    ["Saga Anderson", "Alan Wake", "Dead By Daylight"],
    ["Rose Marigold", "Alan Wake", "Dead By Daylight"],
    ["Mr Scratch", "Alan Wake", "Dead By Daylight"],
    ["Ellen Ripley", "Alien", "Fortnite", "Dead By Daylight"],
    ["Xenomorph", "Alien", "Fortnite", "Dead By Daylight"],
    ["Stan Smith", "American Dad", "Fortnite"],
    ["Francine Smith", "American Dad", "Fortnite"],
    ["Crewmate", "Among Us", "Fortnite", "Balatro"],
    ["Red", "Angry Birds", "Sonic Racing: CrossWorlds"],
    ["Villager", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Isabelle", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Kapp'n", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Perlica", "Arknights: Endfield", "Fortnite"],
    ["Vince", "Art Academy", "Super Smash Bros Ultimate"],
    ["Ezio", "Assassin's Creed", "Fortnite"],
    ["Eivor", "Assassin's Creed", "Fortnite", "Magic: The Gathering"],
    ["Altair", "Assassin's Creed", "Magic: The Gathering"],
    ["Amunet", "Assassin's Creed", "Magic: The Gathering"],
    ["Basim", "Assassin's Creed", "Magic: The Gathering"],
    ["Edward", "Assassin's Creed", "Magic: The Gathering"],
    ["Eren Jaeger", "Attack on Titan", "Fortnite", "Dead By Daylight"],
    ["Mikasa Ackermann", "Attack on Titan", "Fortnite", "Dead By Daylight"],
    ["Levi Ackermann", "Attack on Titan", "Fortnite", "Dead By Daylight"],
    ["Hange", "Attack on Titan", "Dead By Daylight"],
    ["Kenny", "Attack on Titan", "Dead By Daylight"],
    ["Armin", "Attack on Titan", "Dead By Daylight"],
    ["Annie", "Attack on Titan", "Dead By Daylight"],
    ["Historia", "Attack on Titan", "Dead By Daylight"],
    ["Armoured Titan", "Attack on Titan", "Dead By Daylight"],
    ["War Hammer Titan", "Attack on Titan", "Dead By Daylight"],
    ["Jake Sully", "Avatar", "Fortnite"],
    ["Neytiri", "Avatar", "Fortnite"],
    ["Aang", "Avatar: The Last Airbender", "Overwatch", "Fortnite", "Magic: The Gathering", "Sonic Racing: CrossWorlds"],
    ["Korra", "Avatar: The Last Airbender", "Fortnite"],
    ["Ozai", "Avatar: The Last Airbender", "Magic: The Gathering"],
    ["Bumi", "Avatar: The Last Airbender", "Magic: The Gathering"],
    ["Cabbage Merchant", "Avatar: The Last Airbender", "Magic: The Gathering"],
    ["Huu", "Avatar: The Last Airbender", "Magic: The Gathering"],
    ["Zhao", "Avatar: The Last Airbender", "Magic: The Gathering"],
    ["Zuko", "Avatar: The Last Airbender", "Fortnite", "Overwatch", "Magic: The Gathering"],
    ["Toph", "Avatar: The Last Airbender", "Fortnite", "Overwatch", "Magic: The Gathering"],
    ["Sokka", "Avatar: The Last Airbender"],
    ["Katara", "Avatar: The Last Airbender", "Fortnite", "Overwatch", "Sonic Racing: CrossWorlds"],
    ["Azula", "Avatar: The Last Airbender", "Magic: The Gathering"],
    ["Iroh", "Avatar: The Last Airbender"],
    ["Momo", "Avatar: The Last Airbender", "Fortnite"],
    ["Appa", "Avatar: The Last Airbender", "Overwatch", "Fortnite"],
    ["Suki", "Avatar: The Last Airbender", "Overwatch"],
    ["Doc Brown", "Back to the Future", "Ready Player One", "Fortnite"],
    ["Marty McFly", "Back to the Future", "Fortnite"],
    ["Goldie Wilson", "Back to the Future", "Ready Player One"],
    ["Mike Lowrey", "Bad Boys", "Fortnite"],
    ["Banjo", "Banjo-Kazooie", "Super Smash Bros Ultimate"],
    ["Kazooie", "Banjo-Kazooie", "Super Smash Bros Ultimate"],
    ["Tooty", "Banjo-Kazooie", "Super Smash Bros Ultimate"],
    ["Bottles", "Banjo-Kazooie", "Super Smash Bros Ultimate"],
    ["Mumbo Jumbo", "Banjo-Kazooie", "Super Smash Bros Ultimate"],
    ["Jinjos", "Banjo-Kazooie", "Super Smash Bros Ultimate"],
    ["The Mighty Jinjonator", "Banjo-Kazooie", "Super Smash Bros Ultimate"],
    ["Jiggy", "Banjo-Kazooie", "Super Smash Bros Ultimate"],
    ["Gruntilda", "Banjo-Kazooie", "Super Smash Bros Ultimate"],
    ["Buzzbomb", "Banjo-Kazooie", "Super Smash Bros Ultimate"],
    ["Razor", "Battle Breakers", "Fortnite"],
    ["Kurohomura", "Battle Breakers", "Fortnite"],
    ["El Dragon", "BattleBorn", "Ready Player One"],
    ["Attikus", "BattleBorn", "Ready Player One"],
    ["Ambra", "BattleBorn", "Ready Player One"],
    ["Toby", "BattleBorn", "Ready Player One"],
    ["Benedict", "BattleBorn", "Ready Player One"],
    ["Miko", "BattleBorn", "Ready Player One"],
    ["Shayne", "BattleBorn", "Ready Player One"],
    ["Aurox", "BattleBorn", "Ready Player One"],
    ["Pendles", "BattleBorn", "Ready Player One"],
    ["Ordeni", "BattleBorn", "Ready Player One"],
    ["Zitz", "Battletoads", "Ready Player One"],
    ["Rash", "Battletoads", "Ready Player One"],
    ["Pimple", "Battletoads", "Ready Player One"],
    ["Dark Queen", "Battletoads"],
    ["Angelica", "Battletoads"],
    ["Big Blag", "Battletoads"],
    ["Professor T. Bird", "Battletoads"],
    ["Bayonetta", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Rodin", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Gomorrah", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Madama Butterfly", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Jeanne", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Cutie J", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Luka", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Cereza", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Loki", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Balder", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Alraune", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Fortitudo", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Inspired", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Affinity", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Prophet", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Masked Lumen", "Bayonetta", "Super Smash Bros Ultimate"],
    ["Beavis", "Beavis and Butt-Head", "Fortnite"],
    ["Butt-Head", "Beavis and Butt-Head", "Fortnite"],
    ["Beetlejuice", "Beetlejuice", "Ready Player One", "MultiVersus"],
    ["Lydia Deetz", "Beetlejuice"],
    ["Harry the Hunter", "Beetlejuice", "MultiVersus"],
    ["Delia Deetz", "Beetlejuice"],
    ["Charles Deetz", "Beetlejuice"],
    ["Little Jane Butterfield", "Beetlejuice"],
    ["Adam Maitland", "Beetlejuice"],
    ["Barbara Maitland", "Beetlejuice"],
    ["Juno", "Beetlejuice"],
    ["Jane Butterfield", "Beetlejuice"],
    ["Sarah Dean", "Beetlejuice"],
    ["Ben Tennyson", "Ben 10", "Fortnite"],
    ["Gwen Tennyson", "Ben 10", "Fortnite"],
    ["Baymax", "Big Hero 6", "Fortnite"],
    ["Ichigo Kurosaki", "Bleach", "Fortnite"],
    ["Rukia Kuchiki", "Bleach", "Fortnite"],
    ["Orihime Inoue", "Bleach", "Fortnite"],
    ["Uryu Ishida", "Bleach", "Fortnite"],
    ["Yoruichi Shihoin", "Bleach", "Fortnite"],
    ["Kisuke Urahara", "Bleach", "Fortnite"],
    ["Rayne", "BloodRayne", "Ready Player One"],
    ["Dart Monkey", "Bloon TD", "Fortnite"],
    ["Bob Belcher", "Bob's Burger", "Fortnite"],
    ["Linda Belcher", "Bob's Burger", "Fortnite"],
    ["Bomberman", "Bomberman", "Super Smash Bros Ultimate"],
    ["Claptrap", "Borderlands", "Ready Player One", "Fortnite"],
    ["Loader Bot", "Borderlands", "Ready Player One"],
    ["Roland", "Borderlands"],
    ["Lillith", "Borderlands"],
    ["Brick", "Borderlands"],
    ["Psycho Bandit", "Borderlands", "Fortnite"],
    ["Mad Moxxi", "Borderlands", "Fortnite"],
    ["Tung Tung Tung Sahur", "Brainrot Factory", "Fortnite"],
    ["Ballerina Cappuccina", "Brainrot Factory", "Fortnite"],
    ["Grumpy Bear", "Care Bears", "Ready Player One"],
    ["Tenderheart Bear", "Care Bears"],
    ["Cheer Bear", "Care Bears"],
    ["Bedtime Bear", "Care Bears"],
    ["Birthday Bear", "Care Bears"],
    ["Funshine Bear", "Care Bears"],
    ["Love-a-Lot Bear", "Care Bears"],
    ["Wish Bear", "Care Bears"],
    ["Friend Bear", "Care Bears"],
    ["Good Luck Bear", "Care Bears"],
    ["Simon", "Castlevenia", "Super Smash Bros Ultimate", "Dead By Daylight"],
    ["Leon", "Castlevenia", "Dead By Daylight", "Super Smash Bros Ultimate"],
    ["Dracula", "Castlevenia", "Dead By Daylight", "Super Smash Bros Ultimate"],
    ["Alucard", "Castlevenia", "Dead By Daylight"],
    ["Soma", "Castlevenia", "Dead By Daylight"],
    ["Maria", "Castlevenia", "Dead By Daylight", "Super Smash Bros Ultimate"],
    ["Sypha", "Castlevenia", "Dead By Daylight"],
    ["Jonathan Morris", "Castlevenia", "Dead By Daylight"],
    ["Shanoa", "Castlevenia", "Dead By Daylight"],
    ["Richter", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Trevor", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Nathan", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Hugh", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Juste", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Yoko", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Julius", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Hector", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Charlotte", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Shanoa", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Gabriel", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Medusa Head", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Mummy", "Castlevenia", "Super Smash Bros Ultimate"],
    ["The Creature", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Flea Man", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Death", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Carmilla", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Werewolf", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Shaft", "Castlevenia", "Super Smash Bros Ultimate"],
    ["Soma Cruz", "Castlevenia", "Super Smash Bros Ultimate"],
    ["El Chapulín Colorado", "Chespirito", "Fortnite"],
    ["Chucky", "Child's Play", "Ready Player One", "Dead By Daylight", "Magic: The Gathering"],
    ["Jack Santos", "Child's Play"],
    ["Tiffany Valentine", "Child's Play"],
    ["Conan the Barbarian", "Conan the Barbarian", "Ready Player One", "Fortnite"],
    ["Dylan Faden", "Control", "Fortnite"],
    ["Faye Valentine", "Cowboy Bebop", "Overwatch", "Fortnite"],
    ["Spike Spiegel", "Cowboy Bebop", "Overwatch", "Fortnite"],
    ["Jet Black", "Cowboy Bebop", "Overwatch"],
    ["Ed", "Cowboy Bebop", "Overwatch"],
    ["Edward", "Cowboy Bebop"],
    ["Vicious", "Cowboy Bebop"],
    ["Julia", "Cowboy Bebop"],
    ["Ein", "Cowboy Bebop", "Overwatch"],
    ["Axel", "Crazy Taxi", "Sonic Racing: CrossWorlds"],
    ["Kliff", "Crimson Desert", "Fortnite"],
    ["The Traveler", "Cronos", "Fortnite"],
    ["The Birch", "Crypt TV", "Dead By Daylight"],
    ["The Look-See", "Crypt TV", "Dead By Daylight"],
    ["The Mordeo", "Crypt TV", "Dead By Daylight"],
    ["V", "Cyberpunk 2077", "Fortnite"],
    ["Adam Smasher", "Cyberpunk 2077", "Fortnite"],
    ["Johnny Silverhand", "Cyberpunk 2077", "Fortnite", "Balatro"],
    ["Jackie", "Cyberpunk 2077", "Balatro"],
    ["Batman", "DC Comics", "Ready Player One", "Fortnite", "MultiVersus"],
    ["Batgirl", "DC Comics", "Ready Player One", "Fortnite"],
    ["Supergirl", "DC Comics", "Ready Player One", "Fortnite"],
    ["Harley Quinn", "DC Comics", "Ready Player One", "Fortnite", "MultiVersus"],
    ["Firefly", "DC Comics", "Ready Player One"],
    ["Nightwing", "DC Comics", "Ready Player One", "Fortnite"],
    ["Deathstroke", "DC Comics", "Ready Player One", "Fortnite"],
    ["Manbat", "DC Comics", "Ready Player One"],
    ["Catwoman", "DC Comics", "Ready Player One", "Fortnite", "MultiVersus"],
    ["Flash", "DC Comics", "Ready Player One", "Fortnite"],
    ["Aquaman", "DC Comics", "Ready Player One", "Fortnite", "MultiVersus"],
    ["Joker", "DC Comics", "Ready Player One", "Fortnite", "MultiVersus"],
    ["Alfred", "DC Comics", "MultiVersus"],
    ["Shazam", "DC Comics", "MultiVersus"],
    ["King Shark", "DC Comics", "MultiVersus"],
    ["Red X", "DC Comics", "MultiVersus"],
    ["Raven", "DC Comics", "MultiVersus"],
    ["Silky", "DC Comics", "MultiVersus"],
    ["Robin", "DC Comics", "MultiVersus"],
    ["Two Face", "DC Comics", "MultiVersus"],
    ["Starfire", "DC Comics", "MultiVersus"],
    ["Green Lantern", "DC Comics", "MultiVersus", "Magic: The Gathering"],
    ["Control Freak", "DC Comics", "MultiVersus"],
    ["Darkseid", "DC Comics", "MultiVersus"],
    ["Deadshot", "DC Comics", "Ready Player One", "Fortnite"],
    ["Black Manta", "DC Comics", "Fortnite"],
    ["Robin", "DC Comics", "Fortnite"],
    ["Cyborg", "DC Comics", "Fortnite"],
    ["The Engineer", "DC Comics", "Fortnite"],
    ["Mister Terrific", "DC Comics", "Fortnite"],
    ["Poison Ivy", "DC Comics", "Fortnite"],
    ["Raven", "DC Comics", "Fortnite"],
    ["Beast Boy", "DC Comics", "Fortnite"],
    ["Superman", "DC Comics", "Fortnite", "MultiVersus"],
    ["Bloodsport", "DC Comics", "Fortnite"],
    ["Wonder Woman", "DC Comics", "Fortnite", "MultiVersus"],
    ["The Batman Who Laughs", "DC Comics", "Fortnite", "MultiVersus"],
    ["Starfire", "DC Comics", "Fortnite"],
    ["Dreamer", "DC Comics", "Fortnite"],
    ["Black Adams", "DC Comics", "Fortnite", "MultiVersus"],
    ["Peacemaker", "DC Comics", "Fortnite"],
    ["Batman Beyond", "DC Comics", "Fortnite"],
    ["Lobo", "DC Comics", "Fortnite"],
    ["Krypto", "DC Comics", "Fortnite"],
    ["Doom Slayer", "DOOM", "Fortnite", "Super Smash Bros Ultimate"],
    ["Danny Fenton", "Danny Phantom", "Fortnite"],
    ["SAm Manson", "Danny Phantom", "Fortnite"],
    ["Dave the Diver", "Dave the Diver", "Fortnite", "Balatro"],
    ["Cobra", "Dave the Diver", "Balatro"],
    ["Bancho", "Dave the Diver", "Balatro"],
    ["Isaac Clarke", "Dead Space"],
    ["The Scout", "Deep Rock Galactic", "Fortnite"],
    ["Commander Zavala", "Destiny", "Fortnite"],
    ["Ikora Rey", "Destiny", "Fortnite"],
    ["Exo Stranger", "Destiny", "Fortnite"],
    ["Devil", "Devil World", "Super Smash Bros Ultimate"],
    ["Tamagon", "Devil World", "Super Smash Bros Ultimate"],
    ["Mephisto", "Diablo", "Overwatch"],
    ["Lillith", "Diablo", "Overwatch"],
    ["Inarius", "Diablo", "Overwatch"],
    ["The Countess", "Diablo"],
    ["Kormac", "Diablo"],
    ["Hercules", "Disney's Hercules", "Fortnite", "Disney Dreamlight Valley"],
    ["Phil", "Disney's Hercules", "Disney Dreamlight Valley"],
    ["Megara", "Disney's Hercules", "Fortnite"],
    ["Hades", "Disney's Hercules", "Fortnite", "Disney Dreamlight Valley"],
    ["Dalek", "Doctor Who", "Magic: The Gathering"],
    ["Rose Noble", "Doctor Who", "Magic: The Gathering"],
    ["Beep the Meep", "Doctor Who", "Magic: The Gathering"],
    ["The Toymaker", "Doctor Who", "Magic: The Gathering"],
    ["The Doctor", "Doctor Who", "Magic: The Gathering"],
    ["Donkey Kong Jr.", "Donkey Kong", "Ready Player One"],
    ["Donkey Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Diddy Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Klaptrap", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["King K. Rool", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Dracula", "Dracula", "Magic: The Gathering"],
    ["Goku", "Dragon Ball", "Fortnite"],
    ["Vegeta", "Dragon Ball", "Fortnite"],
    ["Bulma", "Dragon Ball", "Fortnite"],
    ["Beerus", "Dragon Ball", "Fortnite"],
    ["Gohan", "Dragon Ball", "Fortnite"],
    ["Piccolo", "Dragon Ball", "Fortnite"],
    ["Frieza", "Dragon Ball", "Fortnite"],
    ["Cell", "Dragon Ball", "Fortnite"],
    ["Android 17", "Dragon Ball", "Fortnite"],
    ["Android 18", "Dragon Ball", "Fortnite"],
    ["Trunks", "Dragon Ball", "Fortnite"],
    ["Hero", "Dragon Quest", "Super Smash Bros Ultimate"],
    ["The Dog", "Duck Hunt", "Super Smash Bros Ultimate"],
    ["The Duck", "Duck Hunt", "Super Smash Bros Ultimate"],
    ["Duke Nukem", "Duke Nukem", "Ready Player One", "Fortnite"],
    ["Botch", "Dumb Ways to Die", "Fortnite"],
    ["Paul Atreides", "Dune", "Fortnite"],
    ["Chani", "Dune", "Fortnite"],
    ["Vecna", "Dungeons and Dragons", "Dead By Daylight"],
    ["Xenk", "Dungeons and Dragons", "Magic: The Gathering"],
    ["Simon", "Dungeons and Dragons", "Magic: The Gathering"],
    ["Forge", "Dungeons and Dragons", "Magic: The Gathering"],
    ["Holga", "Dungeons and Dragons", "Magic: The Gathering"],
    ["Doric", "Dungeons and Dragons", "Magic: The Gathering"],
    ["Edgin", "Dungeons and Dragons", "Magic: The Gathering"],
    ["Acererak", "Dungeons and Dragons", "Magic: The Gathering"],
    ["Xanathar", "Dungeons and Dragons", "Magic: The Gathering"],
    ["Karazikar", "Dungeons and Dragons", "Magic: The Gathering"],
    ["Astarion", "Dungeons and Dragons", "Magic: The Gathering"],
    ["Shadowheart", "Dungeons and Dragons", "Magic: The Gathering"],
    ["Themberchaud", "Dungeons and Dragons", "Magic: The Gathering"],
    ["Ness", "EarthBound", "Super Smash Bros Ultimate"],
    ["Lucas", "EarthBound", "Super Smash Bros Ultimate"],
    ["Jeff", "EarthBound", "Super Smash Bros Ultimate"],
    ["Starman", "EarthBound", "Super Smash Bros Ultimate"],
    ["Ed", "Ed, Edd n Eddy", "Fortnite"],
    ["Edd", "Ed, Edd n Eddy"],
    ["Eddy", "Ed, Edd n Eddy"],
    ["Edward Scissorhands", "Edward Scissorhands", "Fortnite"],
    ["Fernix", "Ember & Blade", "Fortnite"],
    ["Ash Williams", "Evil Dead", "Fortnite", "Dead By Daylight", "Magic: The Gathering"],
    ["Linda", "Evil Dead", "Magic: The Gathering"],
    ["Cheryl Williams", "Evil Dead", "Magic: The Gathering"],
    ["Captain Falcon", "F-Zero", "Super Smash Bros Ultimate"],
    ["Samurai Goroh", "F-Zero", "Super Smash Bros Ultimate"],
    ["Vault Boy", "Fallout", "Fortnite", "Magic: The Gathering"],
    ["Lucy MacLean", "Fallout", "Magic: The Gathering"],
    ["The Ghoul", "Fallout", "Magic: The Gathering"],
    ["Joshua Graham", "Fallout", "Magic: The Gathering"],
    ["Benny", "Fallout", "Magic: The Gathering"],
    ["Maximus", "Fallout", "Magic: The Gathering"],
    ["Peter Griffin", "Family Guy", "Fortnite"],
    ["Lois Griffin", "Family Guy", "Fortnite"],
    ["Cleveland Brown", "Family Guy", "Fortnite"],
    ["The Giant Chicken", "Family Guy", "Fortnite"],
    ["Yuri Kozukata", "Fatal Frame", "Super Smash Bros Ultimate"],
    ["Terry", "Fatal Fury", "Super Smash Bros Ultimate"],
    ["Felix the Cat", "Felix the Cat", "Magic: The Gathering"],
    ["Cloud", "Final Fantasy", "Super Smash Bros Ultimate", "Magic: The Gathering"],
    ["Yuna", "Final Fantasy", "Magic: The Gathering"],
    ["Clive", "Final Fantasy", "Magic: The Gathering"],
    ["Gaia", "Final Fantasy", "Magic: The Gathering"],
    ["Tidus", "Final Fantasy", "Magic: The Gathering"],
    ["Hope", "Final Fantasy", "Magic: The Gathering"],
    ["Noctis", "Final Fantasy", "Magic: The Gathering"],
    ["Vivi", "Final Fantasy", "Magic: The Gathering"],
    ["Aerith", "Final Fantasy", "Magic: The Gathering"],
    ["Yojimbo", "Final Fantasy", "Magic: The Gathering"],
    ["Shiva", "Final Fantasy", "Magic: The Gathering"],
    ["Anima", "Final Fantasy", "Magic: The Gathering"],
    ["Ifrit", "Final Fantasy", "Magic: The Gathering"],
    ["Sephiroth", "Final Fantasy", "Super Smash Bros Ultimate", "Magic: The Gathering"],
    ["Marth", "Fire Emblem", "Super Smash Bros Ultimate"],
    ["Roy", "Fire Emblem", "Super Smash Bros Ultimate"],
    ["Ike", "Fire Emblem", "Super Smash Bros Ultimate"],
    ["Robin", "Fire Emblem", "Super Smash Bros Ultimate"],
    ["Lucina", "Fire Emblem", "Super Smash Bros Ultimate"],
    ["Corrin", "Fire Emblem", "Super Smash Bros Ultimate"],
    ["Chrom", "Fire Emblem", "Super Smash Bros Ultimate"],
    ["Byleth", "Fire Emblem", "Super Smash Bros Ultimate"],
    ["Black Knight", "Fire Emblem", "Super Smash Bros Ultimate"],
    ["Lyn", "Fire Emblem", "Super Smash Bros Ultimate"],
    ["Tiki", "Fire Emblem", "Super Smash Bros Ultimate"],
    ["Glitchtrap", "Five Bights at Freddys", "Dead By Daylight"],
    ["William Afton", "Five Nights at Freddys", "Dead By Daylight"],
    ["Robby the Robot", "Forbidden Planet", "Ready Player One"],
    ["Peely", "Fortnite"],
    ["Cuddle Team Leader", "Fortnite", "Magic: The Gathering"],
    ["Fishstick", "Fortnite", "Magic: The Gathering"],
    ["Skull Trooper", "Fortnite", "Magic: The Gathering"],
    ["Meowsles", "Fortnite", "Magic: The Gathering"],
    ["Hope", "Fortnite"],
    ["Jonesy", "Fortnite", "Magic: The Gathering"],
    ["Frankenstein's Monster", "Frankenstein", "Ready Player One", "Fortnite"],
    ["Frankenstein", "Frankenstein"],
    ["Frankenstein's Bride", "Frankenstein", "Fortnite"],
    ["Jason Voorhees", "Friday the 13th", "Ready Player One", "Fortnite", "MultiVersus", "Dead By Daylight"],
    ["Furby", "Furby", "Magic: The Gathering"],
    ["Fry", "Futurama", "Fortnite"],
    ["Leela", "Futurama", "Fortnite"],
    ["Bender", "Futurama", "Fortnite"],
    ["Baroness", "G.I. Joe", "Overwatch"],
    ["Scarlett", "G.I. Joe", "Overwatch"],
    ["Snake Eyes", "G.I. Joe", "Overwatch", "Fortnite"],
    ["Destro", "G.I. Joe", "Overwatch"],
    ["Cobra Commander", "G.I. Joe", "Overwatch"],
    ["Mr. Game & Watch", "Game & Watch", "Super Smash Bros Ultimate"],
    ["Jon Snow", "Game of Thrones", "Fortnite"],
    ["Arya Stark", "Game of Thrones", "MultiVersus"],
    ["Night King", "Game of Thrones", "Fortnite"],
    ["Daenerys Targaryen", "Game of Thrones", "Fortnite"],
    ["Garfield", "Garfield", "Ready Player One", "Magic: The Gathering"],
    ["Jon", "Garfield", "Magic: The Gathering"],
    ["Odie", "Garfield", "Magic: The Gathering"],
    ["Pooky", "Garfield", "Magic: The Gathering"],
    ["Arlene", "Garfield", "Magic: The Gathering"],
    ["Marcus Fenix", "Gears of War", "Fortnite"],
    ["Kait Diaz", "Gears of War", "Fortnite"],
    ["Jin Sakai", "Ghost of Tsushima", "Magic: The Gathering"],
    ["Atsu", "Ghost of Tsushima", "Magic: The Gathering"],
    ["Slimer", "Ghostbusters", "Magic: The Gathering"],
    ["Marshmallow Man", "Ghostbusters", "Magic: The Gathering"],
    ["Gildedguy", "Gildedguy", "Fortnite"],
    ["Goat", "Goat Simulator", "Fortnite"],
    ["Kratos", "God of War", "Fortnite", "Magic: The Gathering"],
    ["Atreus", "God of War", "Magic: The Gathering"],
    ["Calliope", "God of War", "Magic: The Gathering"],
    ["Mimir", "God of War", "Magic: The Gathering"],
    ["Mechagodzilla", "Godzilla", "Ready Player One", "Fortnite", "King Kong vs Godzilla"],
    ["Godzilla", "Godzilla", "Fortnite", "King Kong vs Godzilla", "Magic: The Gathering"],
    ["Mothra", "Godzilla", "Magic: The Gathering"],
    ["Hedorah", "Godzilla", "Magic: The Gathering"],
    ["Rodan", "Godzilla", "Magic: The Gathering"],
    ["Isaac", "Golden Sun", "Super Smash Bros Ultimate"],
    ["Dude", "Good Guy", "Fortnite"],
    ["Guy", "Good Guy"],
    ["Gizmo", "Gremlins", "MultiVersus"],
    ["Stripe", "Gremlins", "MultiVersus"],
    ["Bubbles", "Gremlins", "MultiVersus"],
    ["Blossom", "Gremlins", "MultiVersus"],
    ["Buttercup", "Gremlins", "MultiVersus"],
    ["Wing Zero", "Gundam", "Overwatch"],
    ["Deathscythe", "Gundam", "Overwatch"],
    ["Tallgeese", "Gundam", "Overwatch"],
    ["Epyon", "Gundam", "Overwatch"],
    ["Duo Maxwell", "Gundam"],
    ["Char Aznable", "Gundam"],
    ["Amuro Ray", "Gundam"],
    ["Lacus Clyne", "Gundam"],
    ["Kira Yamato", "Gundam"],
    ["Mobile Suit Gundam", "Gundam", "Ready Player One"],
    ["Michael Myers", "Halloween", "Fortnite", "Dead By Daylight"],
    ["Laurie Strode", "Halloween", "Dead By Daylight"],
    ["Master Chief", "Halo", "Ready Player One", "Fortnite"],
    ["Carter", "Halo"],
    ["Jorge", "Halo"],
    ["Cortana", "Halo"],
    ["Jun", "Halo"],
    ["Emile", "Halo"],
    ["Kat", "Halo"],
    ["He-Man", "He-Man and the Masters of the Universe", "Ready Player One", "Fortnite"],
    ["She-Ra", "He-Man and the Masters of the Universe", "Fortnite"],
    ["Skeletor", "He-Man and the Masters of the Universe", "Fortnite"],
    ["Prince Adam", "He-Man and the Masters of the Universe"],
    ["Teela", "He-Man and the Masters of the Universe"],
    ["Battlecat", "He-Man and the Masters of the Universe"],
    ["Hello Kitty", "Hello Kitty & Friends", "Overwatch", "Ready Player One", "Animal Crossing"],
    ["Pompompurin", "Hello Kitty & Friends", "Overwatch", "Animal Crossing"],
    ["My Melody", "Hello Kitty & Friends", "Overwatch", "Animal Crossing"],
    ["Kiki", "Hello Kitty & Friends", "Animal Crossing"],
    ["Lala", "Hello Kitty & Friends", "Animal Crossing"],
    ["Cinnamoroll", "Hello Kitty & Friends", "Overwatch", "Animal Crossing"],
    ["Keroppi", "Hello Kitty & Friends", "Overwatch", "Ready Player One", "Animal Crossing"],
    ["Badtz-Maru", "Hello Kitty & Friends", "Ready Player One"],
    ["Chococat", "Hello Kitty & Friends"],
    ["Pochacco", "Hello Kitty & Friends"],
    ["Pekkle", "Hello Kitty & Friends"],
    ["Kuromi", "Hello Kitty & Friends", "Overwatch"],
    ["Chatterer", "Hellraiser", "Dead By Daylight"],
    ["Kafka", "Honkai: Star Rail", "Fortnite"],
    ["Blade", "Honkai: Star Rail", "Fortnite"],
    ["Tom Lizard", "Hoppers", "Fortnite"],
    ["Aloy", "Horizon", "Fortnite", "Magic: The Gathering"],
    ["Ice Climbers", "Ice Climber", "Super Smash Bros Ultimate"],
    ["Indiana Jones", "Indiana Jones", "Ready Player One", "Fortnite"],
    ["Invincible", "Invincible", "Fortnite"],
    ["Omni-Man", "Invincible", "Fortnite"],
    ["Atom Eve", "Invincible", "Fortnite"],
    ["Allen", "Invincible", "Fortnite"],
    ["Dupli-Kate", "Invincible", "Fortnite"],
    ["Chrissie Watkins", "Jaws", "Magic: The Gathering"],
    ["The Shark", "Jaws", "Magic: The Gathering"],
    ["Quint", "Jaws", "Magic: The Gathering"],
    ["John Wick", "John Wick", "Fortnite"],
    ["Sofia Al-Azwar", "John Wick", "Fortnite"],
    ["Sukapon", "Joy Mech Flight", "Super Smash Bros Ultimate"],
    ["Yuji Itadori", "Jujutsu Kaisen", "Fortnite"],
    ["Megumi Fushiguro", "Jujutsu Kaisen", "Fortnite"],
    ["Saturo Gojo", "Jujutsu Kaisen", "Fortnite"],
    ["Nobara Kugisaki", "Jujutsu Kaisen", "Fortnite"],
    ["Ryomen Sukuna", "Jujutsu Kaisen", "Fortnite"],
    ["Toji Fushiguro", "Jujutsu Kaisen", "Fortnite"],
    ["Mahito", "Jujutsu Kaisen", "Fortnite"],
    ["Ian Malcolm", "Jurassic Park", "Magic: The Gathering"],
    ["KAWS Skeleton", "KAWS", "Fortnite"],
    ["Rumi", "KPop Demon Hunters", "Fortnite"],
    ["Mira", "KPop Demon Hunters", "Fortnite"],
    ["Zoey", "KPop Demon Hunters", "Fortnite"],
    ["Jinu", "KPop Demon Hunters", "Fortnite"],
    ["Sable Prince", "Kaeru no Tame ni Kane wa Naru", "Super Smash Bros Ultimate"],
    ["Kafka Hibino", "Kaiju No. 8", "Fortnite"],
    ["Reno Ichikawa", "Kaiju No. 8", "Fortnite"],
    ["Kkoru Shinomiya", "Kaiju No. 8", "Fortnite"],
    ["Fernet", "Kernel Hearts", "Fortnite"],
    ["Pit", "Kid Icarus", "Super Smash Bros Ultimate"],
    ["Palutena", "Kid Icarus", "Super Smash Bros Ultimate"],
    ["Phosphora", "Kid Icarus", "Super Smash Bros Ultimate"],
    ["Beatrix Kiddo", "Kill Bill", "Fortnite"],
    ["Yuki Yubari", "Kill Bill", "Fortnite"],
    ["Gogo Yubari", "Kill Bill", "Fortnite"],
    ["Beatrix Kiddo", "Kill Bill", "Fortnite"],
    ["King Kong", "King Kong", "Ready Player One", "Fortnite", "King Kong vs Godzilla"],
    ["Hank Hill", "King of the Hill", "Fortnite"],
    ["Peggy Hill", "King of the Hill", "Fortnite"],
    ["Sora", "Kingdom Hearts", "Super Smash Bros Ultimate"],
    ["Kirby", "Kirby", "Super Smash Bros Ultimate"],
    ["Nightmare", "Kirby", "Super Smash Bros Ultimate"],
    ["Chef Kawasaki", "Kirby", "Super Smash Bros Ultimate"],
    ["Knuckle Joe", "Kirby", "Super Smash Bros Ultimate"],
    ["Meta Knight", "Kirby", "Super Smash Bros Ultimate"],
    ["King Dedede", "Kirby", "Super Smash Bros Ultimate"],
    ["Jinx", "League of Legends", "Fortnite"],
    ["Viktor", "League of Legends", "Magic: The Gathering"],
    ["Jayce", "League of Legends", "Magic: The Gathering"],
    ["Vi", "League of Legends", "Fortnite"],
    ["Bill Overbeck", "Left 4 Dead", "Dead By Daylight"],
    ["Ellis", "Left 4 Dead", "Dead By Daylight"],
    ["Zoey", "Left 4 Dead", "Dead By Daylight"],
    ["Rochelle", "Left 4 Dead", "Dead By Daylight"],
    ["Francis", "Left 4 Dead", "Dead By Daylight"],
    ["The Employee ", "Lethal Company", "Fortnite"],
    ["Ichiban Kasuga", "Like a Dragon", "Sonic Racing: CrossWorlds"],
    ["Goro Majima", "Like a Dragon", "Sonic Racing: CrossWorlds"],
    ["Marvin the Martian", "Looney Tunes", "Ready Player One"],
    ["Bugs Bunny", "Looney Tunes", "Fortnite", "MultiVersus"],
    ["Daffy Duck", "Looney Tunes", "Fortnite"],
    ["Lola Bunny", "Looney Tunes", "Fortnite"],
    ["Taz", "Looney Tunes", "MultiVersus"],
    ["Porky Pig", "Looney Tunes", "MultiVersus"],
    ["Wile E Coyote", "Looney Tunes"],
    ["Road Runner", "Looney Tunes"],
    ["Tweety", "Looney Tunes", "MultiVersus"],
    ["Foghorn Leghorn", "Looney Tunes", "MultiVersus"],
    ["Gossamer", "Looney Tunes", "MultiVersus"],
    ["Yosemite Sam", "Looney Tunes", "MultiVersus"],
    ["Speedy Gonzales", "Looney Tunes"],
    ["Max Rockatansky", "Mad Max", "Ready Player One"],
    ["Immortan Joe", "Mad Max"],
    ["Lord Humungus", "Mad Max"],
    ["Dementus", "Mad Max"],
    ["Thalia", "Magic: The Gathering"],
    ["Mario", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Wario", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Adhley", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Luigi", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Peach", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Bowser", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Rosalina", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Luma", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Bowser Jr.", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Yoshi", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Daisy", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Chain Chomp", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Hammer Bro", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Thwomp", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Waluigi", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Piranha Plant", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Toadette", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Captain Toad", "Mario Bros", "Super Smash Bros Ultimate"],
    ["Thanos", "Marvel Comics", "Fortnite"],
    ["Magik", "Marvel Comics", "Fortnite"],
    ["Luna Snow", "Marvel Comics", "Fortnite"],
    ["Star-Lord", "Marvel Comics", "Fortnite"],
    ["Black Widow", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Deadpool", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Collector", "Marvel Comics", "Magic: The Gathering"],
    ["Cable", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Domino", "Marvel Comics", "Fortnite"],
    ["Psylocke", "Marvel Comics", "Fortnite"],
    ["Captain America", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Galactus", "Marvel Comics", "Fortnite"],
    ["Thor", "Marvel Comics", "Fortnite"],
    ["Venom", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Ghost Rider", "Marvel Comics", "Fortnite"],
    ["Daredevil", "Marvel Comics", "Fortnite"],
    ["Blade", "Marvel Comics", "Fortnite"],
    ["Silver Surfer", "Marvel Comics", "Fortnite"],
    ["Storm", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Groot", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Wolverine", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Talon", "Marvel Comics", "Magic: The Gathering"],
    ["She-Hulk", "Marvel Comics", "Fortnite"],
    ["Tony Stark", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Mystique", "Marvel Comics", "Fortnite"],
    ["Dr. Doom", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Rocket", "Marvel Comics", "Fortnite"],
    ["Captain Marvel", "Marvel Comics", "Fortnite"],
    ["Black Panther", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Ulysses Klaw", "Marvel Comics", "Magic: The Gathering"],
    ["Taskmaster", "Marvel Comics", "Fortnite"],
    ["Green Arrow", "Marvel Comics", "Fortnite"],
    ["Ant-Man", "Marvel Comics", "Fortnite"],
    ["Loki", "Marvel Comics", "Fortnite"],
    ["Gamora", "Marvel Comics", "Fortnite"],
    ["Shang-Chi", "Marvel Comics", "Fortnite"],
    ["Carnage", "Marvel Comics", "Fortnite"],
    ["Eddie Brock", "Marvel Comics", "Fortnite"],
    ["Jean Grey", "Marvel Comics", "Fortnite"],
    ["Nick Fury", "Marvel Comics", "Fortnite"],
    ["Spider-Man", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["MJ", "Marvel Comics", "Fortnite"],
    ["Kate Bishop", "Marvel Comics", "Fortnite"],
    ["Clint Barton", "Marvel Comics", "Fortnite"],
    ["Green Goblin", "Marvel Comics", "Fortnite"],
    ["Rogue", "Marvel Comics", "Fortnite"],
    ["Gambit", "Marvel Comics", "Fortnite"],
    ["Doctor Strange", "Marvel Comics", "Fortnite"],
    ["Prowler", "Marvel Comics", "Fortnite"],
    ["Moon Night", "Marvel Comics", "Fortnite"],
    ["Scarlet Witch", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Hammerhead", "Marvel Comics", "Magic: The Gathering"],
    ["Uatu", "Marvel Comics", "Magic: The Gathering"],
    ["Tippy-Toe", "Marvel Comics", "Magic: The Gathering"],
    ["Squirrel Girl", "Marvel Comics", "Magic: The Gathering"],
    ["Jane Foster", "Marvel Comics", "Fortnite"],
    ["Spider-Gwen", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Iron Man Zero", "Marvel Comics", "Fortnite"],
    ["X-23", "Marvel Comics", "Fortnite"],
    ["Hulk", "Marvel Comics", "Fortnite"],
    ["Sam Wilson", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Miles Morales", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Miguel Ohara", "Marvel Comics", "Fortnite"],
    ["Drax", "Marvel Comics", "Fortnite"],
    ["Mantis", "Marvel Comics", "Fortnite"],
    ["Hela", "Marvel Comics", "Fortnite"],
    ["Sylvie", "Marvel Comics", "Fortnite"],
    ["Magneto", "Marvel Comics", "Fortnite"],
    ["Cyclops", "Marvel Comics", "Fortnite"],
    ["Jubilee", "Marvel Comics", "Fortnite"],
    ["White Widow", "Marvel Comics", "Fortnite"],
    ["Winter Soldier", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Toro", "Marvel Comics", "Magic: The Gathering"],
    ["Namor", "Marvel Comics", "Magic: The Gathering"],
    ["Colossus", "Marvel Comics", "Fortnite"],
    ["Agony", "Marvel Comics", "Fortnite"],
    ["Spider-Woman", "Marvel Comics", "Fortnite"],
    ["Mephisto", "Marvel Comics", "Fortnite"],
    ["Black Cat", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["The Lizard", "Marvel Comics", "Magic: The Gathering"],
    ["Electro", "Marvel Comics", "Magic: The Gathering"],
    ["Doctor Octopus", "Marvel Comics", "Magic: The Gathering"],
    ["Mysterio", "Marvel Comics", "Fortnite"],
    ["Shuri", "Marvel Comics", "Fortnite"],
    ["Emma Frost", "Marvel Comics", "Fortnite"],
    ["Gwenpool", "Marvel Comics", "Fortnite", "Magic: The Gathering"],
    ["Jeff the Shark", "Marvel Comics", "Magic: The Gathering"],
    ["War Machine", "Marvel Comics", "Fortnite"],
    ["She Venom", "Marvel Comics", "Fortnite"],
    ["Spider-Man Noir", "Marvel Comics", "Fortnite"],
    ["Mister Fantastic", "Marvel Comics", "Fortnite"],
    ["Invisible Woman", "Marvel Comics", "Fortnite"],
    ["Human Torch", "Marvel Comics", "Fortnite"],
    ["The Thing", "Marvel Comics", "Fortnite"],
    ["Spider-Punk", "Marvel Rivals", "Fortnite", "Magic: The Gathering"],
    ["Peter B. Parker", "Marvel Rivals", "Fortnite"],
    ["Commander Shepard", "Mass Effect", "Ready Player One"],
    ["James Vega", "Mass Effect"],
    ["Garrus Valkarian", "Mass Effect"],
    ["Mega Man", "Mega Man", "Super Smash Bros Ultimate", "Sonic Racing: CrossWorlds"],
    ["Proto Man", "Mega Man", "Sonic Racing: CrossWorlds"],
    ["Dr. Wily", "Mega Man", "Super Smash Bros Ultimate"],
    ["Zero", "Mega Man", "Super Smash Bros Ultimate"],
    ["Solid Snake", "Metal Gear", "Fortnite", "Super Smash Bros Ultimate"],
    ["Gray Fox", "Metal Gear", "Super Smash Bros Ultimate"],
    ["Raiden", "Metal Gear"],
    ["Samus", "Metroid", "Ready Player One", "Super Smash Bros Ultimate"],
    ["Ripley", "Metroid", "Super Smash Bros Ultimate"],
    ["Metroid", "Metroid", "Super Smash Bros Ultimate"],
    ["Mother Brain", "Metroid", "Super Smash Bros Ultimate"],
    ["Mickey Mouse", "Mickey Mouse", "Fortnite", "Kingdm Hearts", "Disney Dreamlight Valley", "The Sword in the Stone"],
    ["Goofy", "Mickey Mouse", "Fortnite", "Kingdom Hearts", "Disney Dreamlight Valley"],
    ["Donald Duck", "Mickey Mouse", "Fortnite", "Kingdom Hearts", "Disney Dreamlight Valley"],
    ["Daisy", "Mickey Mouse", "Disney Dreamlight Valley"],
    ["Minnie Mouse", "Mickey Mouse", "Disney Dreamlight Valley"],
    ["Scrooge McDuck", "Mickey Mouse", "Disney Dreamlight Valley"],
    ["Steve", "Minecraft", "Super Smash Bros Ultimate", "Sonic Racing: CrossWorlds"],
    ["Alex", "Minecraft", "Super Smash Bros Ultimate", "Sonic Racing: CrossWorlds"],
    ["Creeper", "Minecraft", "Sonic Racing: CrossWorlds"],
    ["Kelsier", "Mistborn", "Fortnite"],
    ["Rathalos", "Monster Hunter", "Super Smash Bros Ultimate", "Magic: The Gathering"],
    ["Lagiacrus", "Monster Hunter", "Magic: The Gathering"],
    ["Fatalis", "Monster Hunter", "Magic: The Gathering"],
    ["Nergigante", "Monster Hunter", "Magic: The Gathering"],
    ["Zinogre", "Monster Hunter", "Magic: The Gathering"],
    ["Malzeno", "Monster Hunter", "Magic: The Gathering"],
    ["Kushala Daora", "Monster Hunter", "Magic: The Gathering"],
    ["Magnamalo", "Monster Hunter", "Magic: The Gathering"],
    ["Tobi-Kadachi", "Monster Hunter", "Magic: The Gathering"],
    ["Yian Garuga", "Monster Hunter", "Magic: The Gathering"],
    ["Seregios", "Monster Hunter", "Magic: The Gathering"],
    ["Gore Magala", "Monster Hunter", "Magic: The Gathering"],
    ["Brachydios", "Monster Hunter", "Magic: The Gathering"],
    ["Nargacuga", "Monster Hunter", "Magic: The Gathering"],
    ["Velkhana", "Monster Hunter", "Magic: The Gathering"],
    ["Tim the Enchanter", "Monty Python", "Magic: The Gathering"],
    ["Dead Collector", "Monty Python", "Magic: The Gathering"],
    ["King Arthur", "Monty Python", "Magic: The Gathering"],
    ["The Black Knight", "Monty Python", "Magic: The Gathering"],
    ["Sir Robin", "Monty Python", "Magic: The Gathering"],
    ["The Bridgekeeper", "Monty Python", "Magic: The Gathering"],
    ["Sir Bedivere", "Monty Python", "Magic: The Gathering"],
    ["Killer Rabbit", "Monty Python", "Magic: The Gathering"],
    ["Scorpion", "Mortal Kombat", "Ready Player One", "Fortnite"],
    ["Kitana", "Mortal Kombat", "Ready Player One", "Fortnite"],
    ["Sub-Zero", "Mortal Kombat", "Ready Player One", "Fortnite"],
    ["Raiden", "Mortal Kombat", "Ready Player One", "Fortnite"],
    ["Liu Kang", "Mortal Kombat"],
    ["Johnny Cage", "Mortal Kombat"],
    ["Sheeva", "Mortal Kombat"],
    ["Cyrax", "Mortal Kombat"],
    ["Sonya Blade", "Mortal Kombat"],
    ["Goro", "Mortal Kombat", "Ready Player One"],
    ["Reindog", "MultiVersus"],
    ["All Might", "My Hero Academia", "Overwatch", "Fortnite"],
    ["Uravity", "My Hero Academia", "Overwatch", "Fortnite"],
    ["Deku", "My Hero Academia", "Overwatch", "Fortnite"],
    ["Hikimo Toga", "My Hero Academia", "Overwatch", "Fortnite"],
    ["Shigaraki", "My Hero Academia", "Overwatch", "Fortnite"],
    ["Bakugo", "My Hero Academia", "Fortnite"],
    ["Todoroki", "My Hero Academia", "Fortnite"],
    ["Kirishima", "My Hero Academia", "Fortnite"],
    ["Mina Ashido", "My Hero Academia", "Fortnite"],
    ["Dabi", "My Hero Academia", "Fortnite"],
    ["Applejack", "My Little Pony", "Magic: The Gathering"],
    ["Rarity", "My Little Pony", "Magic: The Gathering"],
    ["Twilight Sparkle", "My Little Pony", "Magic: The Gathering"],
    ["Spike", "My Little Pony", "Magic: The Gathering"],
    ["Princess Luna", "My Little Pony", "Magic: The Gathering"],
    ["Princess Celestia", "My Little Pony", "Magic: The Gathering"],
    ["Fluttershy", "My Little Pony", "Magic: The Gathering"],
    ["Pinkie Pie", "My Little Pony", "Magic: The Gathering"],
    ["Rainbow Dash", "My Little Pony", "Magic: The Gathering"],
    ["Discord", "My Little Pony", "Magic: The Gathering"],
    ["Feria Shen", "Naraka: Bladepoint", "Overwatch"],
    ["Wei Qing", "Naraka: Bladepoint", "Overwatch"],
    ["Cyra", "Naraka: Bladepoint", "Overwatch"],
    ["Yueshan", "Naraka: Bladepoint", "Overwatch"],
    ["Viper Ning", "Naraka: Bladepoint", "Overwatch"],
    ["Wuchen", "Naraka: Bladepoint", "Overwatch"],
    ["Naruto", "Naruto", "Fortnite"],
    ["Sasuke", "Naruto", "Fortnite"],
    ["Sakura", "Naruto", "Fortnite"],
    ["Kakashi", "Naruto", "Fortnite"],
    ["Hinata", "Naruto", "Fortnite"],
    ["Gaara", "Naruto", "Fortnite"],
    ["Itachi", "Naruto", "Fortnite"],
    ["Orochimaru", "Naruto", "Fortnite"],
    ["Naughty Bear", "Naughty Bear: Panic in Paradise", "Dead By Daylight"],
    ["Rei Ayanami", "Neon Genesis Evangalion", "Sonic Racing: CrossWorlds"],
    ["Asuka Shikinami", "Neon Genesis Evangalion", "Sonic Racing: CrossWorlds"],
    ["Aisha", "Neopets", "Fortnite"],
    ["NiGHTS", "NiGHTS", "Sonic Racing: CrossWorlds"],
    ["Arcade Bunny", "Nintendo Badge Arcade", "Super Smash Bros Ultimate"],
    ["Saitama", "One Punch Man", "Overwatch", "Fortnite"],
    ["Genos", "One Punch Man", "Overwatch", "Fortnite"],
    ["Terrible Tornado", "One Punch Man", "Overwatch", "Fortnite"],
    ["Fubuki", "One Punch Man", "Overwatch"],
    ["Sonic", "One Punch Man"],
    ["King", "One Punch Man"],
    ["Blast", "One Punch Man"],
    ["Garou", "One Punch Man", "Overwatch"],
    ["Mumen Rider", "One Punch Man", "Overwatch"],
    ["Boros", "One Punch Man", "Overwatch"],
    ["Shion", "Overwatch"],
    ["Ana", "Overwatch"],
    ["Anran", "Overwatch"],
    ["Ashe", "Overwatch"],
    ["Baptiste", "Overwatch"],
    ["Bastion", "Overwatch"],
    ["Brigitte", "Overwatch"],
    ["D.Va", "Overwatch", "Fortnite"],
    ["Cassidy", "Overwatch"],
    ["Domina", "Overwatch"],
    ["Doomfist", "Overwatch"],
    ["Echo", "Overwatch"],
    ["Emre", "Overwatch"],
    ["Freya", "Overwatch"],
    ["Genji", "Overwatch", "Fortnite"],
    ["Hanzo", "Overwatch"],
    ["Hazard", "Overwatch"],
    ["Illari", "Overwatch"],
    ["Hanzo", "Overwatch"],
    ["Hazard", "Overwatch"],
    ["Jetpack Cat", "Overwatch"],
    ["Junker Queen", "Overwatch"],
    ["Junkrat", "Overwatch", "Rick and Morty"],
    ["Juno", "Overwatch"],
    ["Kiriko", "Overwatch"],
    ["Lifeweaver", "Overwatch"],
    ["Lucio", "Overwatch"],
    ["Mauga", "Overwatch"],
    ["Mei", "Overwatch"],
    ["Mercy", "Overwatch", "Fortnite"],
    ["Mizuki", "Overwatch"],
    ["Moira", "Overwatch"],
    ["Orisa", "Overwatch"],
    ["Pharah", "Overwatch"],
    ["Ramattra", "Overwatch"],
    ["Reaper", "Overwatch"],
    ["Reinhardt", "Overwatch"],
    ["Roadhog", "Overwatch", "Rick and Morty"],
    ["Sierra", "Overwatch"],
    ["Sigma", "Overwatch"],
    ["Sojourn", "Overwatch"],
    ["Soldier: 76", "Overwatch"],
    ["Sombra", "Overwatch"],
    ["Symmetra", "Overwatch"],
    ["Torbjorn", "Overwatch"],
    ["Tracer", "Overwatch", "Fortnite", "Ready Player One"],
    ["Winston", "Overwatch"],
    ["Wrecking Ball", "Overwatch"],
    ["Zarya", "Overwatch"],
    ["Zenyatta", "Overwatch"],
    ["Wuyang", "Overwatch"],
    ["PEAK Scout", "PEAK", "Fortnite"],
    ["Pac-Man", "Pac-Man", "Ready Player One", "Fortnite", "Super Smash Bros Ultimate", "Sonic Racing: CrossWorlds"],
    ["Blinky", "Pac-Man", "Fortnite", "Super Smash Bros Ultimate", "Sonic Racing: CrossWorlds"],
    ["Inky", "Pac-Man", "Fortnite", "Super Smash Bros Ultimate", "Sonic Racing: CrossWorlds"],
    ["Pinky", "Pac-Man", "Fortnite", "Super Smash Bros Ultimate", "Sonic Racing: CrossWorlds"],
    ["Clyde", "Pac-Man", "Fortnite", "Super Smash Bros Ultimate", "Sonic Racing: CrossWorlds"],
    ["Mrs. Pac-Man", "Pac-Man"],
    ["Queen", "Persona", "Overwatch"],
    ["Skull", "Persona", "Overwatch"],
    ["Fox", "Persona", "Overwatch"],
    ["Panther", "Persona", "Overwatch"],
    ["Joker", "Persona", "Overwatch", "Super Smash Bros Ultimate", "Sonic Racing: CrossWorlds"],
    ["Yukari Takeba", "Persona"],
    ["Junpei Iori", "Persona"],
    ["Akihiko Sanada", "Persona"],
    ["Itsuru Kirijo", "Persona"],
    ["Yu Narukami", "Persona"],
    ["Captain Hook", "Peter Pan", "Fortnite"],
    ["Dr. Doofenshmirtz", "Phineas and Ferb", "Fortnite"],
    ["Perry the Platipus", "Phineas and Ferb", "Fortnite"],
    ["Olimar", "Pikmin", "Super Smash Bros Ultimate"],
    ["Pikmin", "Pikmin", "Super Smash Bros Ultimate"],
    ["Burrowing Snagret", "Pikmin", "Super Smash Bros Ultimate"],
    ["Jack Sparrow", "Pirates of the Caribbean", "Fortnite"],
    ["Elizabeth Swann", "Pirates of the Caribbean", "Fortnite"],
    ["Captain Barbossa", "Pirates of the Caribbean", "Fortnite"],
    ["Davy Jones", "Pirates of the Caribbean", "Fortnite"],
    ["Pikachu", "Pokemon", "Super Smash Bros Ultimate"],
    ["Detective Pikachu", "Pokemon", "Super Smash Bros Ultimate"],
    ["Jigglypuff", "Pokemon", "Super Smash Bros Ultimate"],
    ["Mewtwo", "Pokemon", "Super Smash Bros Ultimate"],
    ["Red", "Pokemon", "Super Smash Bros Ultimate"],
    ["Green", "Pokemon", "Super Smash Bros Ultimate"],
    ["Squirtle", "Pokemon", "Super Smash Bros Ultimate"],
    ["Ivysaur", "Pokemon", "Super Smash Bros Ultimate"],
    ["Charizard", "Pokemon", "Super Smash Bros Ultimate"],
    ["Lucario", "Pokemon", "Super Smash Bros Ultimate"],
    ["Greninja", "Pokemon", "Super Smash Bros Ultimate"],
    ["Incineroar", "Pokemon", "Super Smash Bros Ultimate"],
    ["Raichu", "Pokemon", "Super Smash Bros Ultimate"],
    ["Vulpix", "Pokemon", "Super Smash Bros Ultimate"],
    ["Meowth", "Pokemon", "Super Smash Bros Ultimate"],
    ["Abra", "Pokemon", "Super Smash Bros Ultimate"],
    ["Electrode", "Pokemon", "Super Smash Bros Ultimate"],
    ["Exeggutor", "Pokemon", "Super Smash Bros Ultimate"],
    ["Goldeen", "Pokemon", "Super Smash Bros Ultimate"],
    ["Staryu", "Pokemon", "Super Smash Bros Ultimate"],
    ["Ditto", "Pokemon", "Super Smash Bros Ultimate"],
    ["Eevee", "Pokemon", "Super Smash Bros Ultimate"],
    ["Snorlax", "Pokemon", "Super Smash Bros Ultimate"],
    ["Moltres", "Pokemon", "Super Smash Bros Ultimate"],
    ["Mew", "Pokemon", "Super Smash Bros Ultimate"],
    ["Togepi", "Pokemon", "Super Smash Bros Ultimate"],
    ["Bellossom", "Pokemon", "Super Smash Bros Ultimate"],
    ["Scizor", "Pokemon", "Super Smash Bros Ultimate"],
    ["Entei", "Pokemon", "Super Smash Bros Ultimate"],
    ["Suicune", "Pokemon", "Super Smash Bros Ultimate"],
    ["Lugia", "Pokemon", "Super Smash Bros Ultimate"],
    ["Gardevoir", "Pokemon", "Super Smash Bros Ultimate"],
    ["Metagross", "Pokemon", "Super Smash Bros Ultimate"],
    ["Latias", "Pokemon", "Super Smash Bros Ultimate"],
    ["Latios", "Pokemon", "Super Smash Bros Ultimate"],
    ["Kyogre", "Pokemon", "Super Smash Bros Ultimate"],
    ["Deoxys", "Pokemon", "Super Smash Bros Ultimate"],
    ["Abomasnow", "Pokemon", "Super Smash Bros Ultimate"],
    ["Palkia", "Pokemon", "Super Smash Bros Ultimate"],
    ["Giratina", "Pokemon", "Super Smash Bros Ultimate"],
    ["Drakrai", "Pokemon", "Super Smash Bros Ultimate"],
    ["Arceus", "Pokemon", "Super Smash Bros Ultimate"],
    ["Victini", "Pokemon", "Super Smash Bros Ultimate"],
    ["Snivy", "Pokemon", "Super Smash Bros Ultimate"],
    ["Oshawott", "Pokemon", "Super Smash Bros Ultimate"],
    ["Zoroark", "Pokemon", "Super Smash Bros Ultimate"],
    ["Kyurem", "Pokemon", "Super Smash Bros Ultimate"],
    ["Keldeo", "Pokemon", "Super Smash Bros Ultimate"],
    ["Meloetta", "Pokemon", "Super Smash Bros Ultimate"],
    ["Genesect", "Pokemon", "Super Smash Bros Ultimate"],
    ["Chespin", "Pokemon", "Super Smash Bros Ultimate"],
    ["Fennekin", "Pokemon", "Super Smash Bros Ultimate"],
    ["Fletchling", "Pokemon", "Super Smash Bros Ultimate"],
    ["Spewpa", "Pokemon", "Super Smash Bros Ultimate"],
    ["Gogoat", "Pokemon", "Super Smash Bros Ultimate"],
    ["Swirlix", "Pokemon", "Super Smash Bros Ultimate"],
    ["Inkay", "Pokemon", "Super Smash Bros Ultimate"],
    ["Dedenne", "Pokemon", "Super Smash Bros Ultimate"],
    ["Xerneas", "Pokemon", "Super Smash Bros Ultimate"],
    ["Bewear", "Pokemon", "Super Smash Bros Ultimate"],
    ["Pyukumuku", "Pokemon", "Super Smash Bros Ultimate"],
    ["Togedemaru", "Pokemon", "Super Smash Bros Ultimate"],
    ["Mimikyu", "Pokemon", "Super Smash Bros Ultimate"],
    ["Tapu Koko", "Pokemon", "Super Smash Bros Ultimate"],
    ["Solgaleo", "Pokemon", "Super Smash Bros Ultimate"],
    ["Lunala", "Pokemon", "Super Smash Bros Ultimate"],
    ["Marshadow", "Pokemon", "Super Smash Bros Ultimate"],
    ["Huggy Wuggy", "Poppy Playtime", "Fortnite"],
    ["White Dino Ranger", "Power Rangers", "Fortnite"],
    ["Black Dino Ranger", "Power Rangers", "Fortnite"],
    ["Green Ranger", "Power Rangers", "Fortnite"],
    ["Dino Megazord", "Power Rangers", "Fortnite"],
    ["Blue Ranger", "Power Rangers", "Fortnite"],
    ["Pink Ranger", "Power Rangers", "Fortnite"],
    ["Black Ranger", "Power Rangers", "Fortnite"],
    ["Yellow Ranger", "Power Rangers", "Fortnite"],
    ["Lord Zedd", "Power Rangers", "Fortnite"],
    ["Commander White", "Project YoRHa", "Overwatch"],
    ["A2", "Project YoRHa", "Overwatch"],
    ["9S", "Project YoRHa", "Overwatch"],
    ["2B", "Project YoRHa", "Overwatch"],
    ["Adam", "Project YoRHa", "Overwatch"],
    ["Emil", "Project YoRHa", "Overwatch"],
    ["Eve", "Project YoRHa"],
    ["Devola", "Project YoRHa"],
    ["Kaine", "Project YoRHa"],
    ["Yonah", "Project YoRHa"],
    ["Vincent Vega", "Pulp Fiction", "Fortnite"],
    ["Jules Winnfield", "Pulp Fiction", "Fortnite"],
    ["Little Mac", "Punch Out", "Super Smash Bros Ultimate"],
    ["Little Mac", "Punch Out", "Super Smash Bros Ultimate"],
    ["Arle Nadja", "Puyo", "Sonic Racing: CrossWorlds"],
    ["Semibot", "R.E.P.O.", "Fortnite"],
    ["R.O.B.", "R.O.B.", "Super Smash Bros Ultimate"],
    ["Coach Gabi", "REMATCH", "Fortnite"],
    ["Tubarao", "Raibow Six Siege", "Dead By Daylight"],
    ["Tubarao", "Raibow Six Siege", "Dead By Daylight"],
    ["Wamai", "Raibow Six Siege", "Dead By Daylight"],
    ["Blitz", "Raibow Six Siege", "Dead By Daylight"],
    ["John Rambo", "Ranbo", "Fortnite"],
    ["Mordecai", "Regular Show", "Fortnite"],
    ["Skips", "Regular Show", "Fortnite"],
    ["Rigby", "Regular Show", "Fortnite"],
    ["Jill Valentine", "Resident Evil", "Ready Player One", "Fortnite", "Dead By Daylight"],
    ["Chris Redfield", "Resident Evil", "Fortnite"],
    ["Leon Kennedy", "Resident Evil", "Fortnite", "Dead By Daylight"],
    ["Claire Redfield", "Resident Evil", "Fortnite"],
    ["Nemesis", "Resident Evil", "Dead By Daylight"],
    ["Albert Wesker", "Resident Evil", "Dead By Daylight"],
    ["Ada Wong", "Resident Evil", "Dead By Daylight"],
    ["Sheva Alomar", "Resident Evil", "Dead By Daylight"],
    ["Carlos Oliveira", "Resident Evil", "Dead By Daylight"],
    ["HUNK", "Resident Evil", "Dead By Daylight"],
    ["William Birkin", "Resident Evil", "Dead By Daylight"],
    ["Grace Ashcroft", "Resident Evil", "Fortnite"],
    ["Rick", "Rick and Morty", "Fortnite", "MultiVersus"],
    ["Squanchy", "Rick and Morty", "Fortnite"],
    ["Mr. Poopy Butthole", "Rick and Morty", "Fortnite"],
    ["Morty", "Rick and Morty", "Fortnite", "MultiVersus"],
    ["Mr. Meeseeks", "Rick and Morty", "Fortnite", "MultiVersus"],
    ["Summer", "Rick and Morty", "Fortnite"],
    ["Snowball", "Rick and Morty", "Fortnite"],
    ["Beth", "Rick and Morty", "Fortnite"],
    ["Jerry", "Rick and Morty"],
    ["Prime Rick", "Rick and Morty", "Fortnite"],
    ["Sadako Yamamura", "Ring", "Dead By Daylight"],
    ["Yoichi Asakawa", "Ring", "Dead By Daylight"],
    ["Robocop", "Robocop", "Ready Player One", "Fortnite"],
    ["Octane", "Rocket League", "Fortnite"],
    ["Adonis Creed", "Rocky", "Fortnite"],
    ["Amigo", "Samba de Amigo", "Sonic Racing: CrossWorlds"],
    ["Samurai Jack", "Samurai Jack", "Fortnite", "MultiVersus"],
    ["Billy", "Saw", "Fortnite"],
    ["Amanda Young", "Saw", "Dead By Daylight"],
    ["David Tapp", "Saw", "Dead By Daylight"],
    ["Scooby-Doo", "Scooby-Doo", "Fortnite", "MultiVersus"],
    ["Shaggy", "Scooby-Doo", "Fortnite", "MultiVersus"],
    ["Velma", "Scooby-Doo", "Fortnite", "MultiVersus"],
    ["Daphne", "Scooby-Doo", "Fortnite"],
    ["Fred", "Scooby-Doo", "Fortnite", "MultiVersus"],
    ["Ghost Face", "Scream", "Fortnite", "Dead By Daylight"],
    ["Cookie Monster", "Sesamie Street", "Ready Player One"],
    ["Elmo", "Sesamie Street"],
    ["Sherrif", "Sherrif", "Super Smash Bros Ultimate"],
    ["Shovel Night", "Shovel Night", "Super Smash Bros Ultimate"],
    ["Pyramid Head", "Silent Hill", "Dead By Daylight"],
    ["Cheryl", "Silent Hill", "Dead By Daylight"],
    ["Lisa", "Silent Hill", "Dead By Daylight"],
    ["Cybil", "Silent Hill", "Dead By Daylight"],
    ["James", "Silent Hill", "Dead By Daylight"],
    ["Maria", "Silent Hill", "Dead By Daylight"],
    ["Dr. Wright", "SimCity", "Super Smash Bros Ultimate"],
    ["Plungerman", "Skibidi Toilet", "Fortnite"],
    ["Skibidi Toilet", "Skibidi Toilet", "Fortnite"],
    ["Maleficent", "Sleeping Beauty", "Fortnite", "Disney Dreamlight Valley"],
    ["Sung Jinwoo", "Solo Leveling", "Fortnite"],
    ["Cha Hae-In", "Solo Leveling", "Fortnite"],
    ["Blood-Red Commander Igris", "Solo Leveling", "Fortnite"],
    ["Sonic", "Sonic the Hedgehog", "Ready Player One", "Super Smash Bros Ultimate", "Magic: The Gathering", "Sonic Racing: CrossWorlds"],
    ["Tails", "Sonic the Hedgehog", "Magic: The Gathering", "Sonic Racing: CrossWorlds"],
    ["Rouge", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Amy", "Sonic the Hedgehog", "Magic: The Gathering", "Sonic Racing: CrossWorlds"],
    ["Dr. Eggman", "Sonic the Hedgehog", "Magic: The Gathering", "Sonic Racing: CrossWorlds"],
    ["Knuckles", "Sonic the Hedgehog", "Super Smash Bros Ultimate", "Magic: The Gathering", "Sonic Racing: CrossWorlds"],
    ["Silver", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Shadow", "Sonic the Hedgehog", "Super Smash Bros Ultimate", "Magic: The Gathering", "Sonic Racing: CrossWorlds"],
    ["Cream", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Cheese", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Big the Cat", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Blaze", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["E-123 Omega", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Vector the Crocodile", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Espio", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Charmy Bee", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Zavok", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Zazz", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Metal Sonic", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Egg Pawn", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Sage", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Jet", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Wave", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Storm", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Tangle", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Whisper", "Sonic the Hedgehog", "Sonic Racing: CrossWorlds"],
    ["Eric Cartman", "South Park", "Fortnite"],
    ["Kenny McCormick", "South Park", "Fortnite"],
    ["Kyle Broflovski", "South Park", "Fortnite"],
    ["Stan Marsh", "South Park", "Fortnite"],
    ["Butter Scotch", "South Park", "Fortnite"],
    ["Towelie", "South Park", "Fortnite"],
    ["Spawn", "Spawn", "Ready Player One"],
    ["Inkling", "Splatoon", "Super Smash Bros Ultimate"],
    ["Callie", "Splatoon", "Super Smash Bros Ultimate"],
    ["Marie", "Splatoon", "Super Smash Bros Ultimate"],
    ["SpongeBob SquarePants", "SpongeBob SquarePants", "Fortnite", "Magic: The Gathering", "Sonic Racing: CrossWorlds"],
    ["Patrick Star", "SpongeBob SquarePants", "Fortnite", "Magic: The Gathering", "Sonic Racing: CrossWorlds"],
    ["Plankton", "SpongeBob SquarePants", "Magic: The Gathering"],
    ["Mr. Krabs", "SpongeBob SquarePants", "Magic: The Gathering"],
    ["Squidwards", "SpongeBob SquarePants", "Magic: The Gathering"],
    ["Gary", "SpongeBob SquarePants", "Magic: The Gathering"],
    ["Sandy Cheeks", "SpongeBob SquarePants", "Magic: The Gathering"],
    ["Fred", "SpongeBob SquarePants", "Magic: The Gathering"],
    ["Seong Gi-hun", "Squid Game", "Fortnite"],
    ["Kang Sae-byeok", "Squid Game", "Fortnite"],
    ["Front Man", "Squid Game", "Fortnite"],
    ["Fox", "Star Fox", "Ready Player One", "Super Smash Bros Ultimate"],
    ["Wolf", "Star Fox", "Super Smash Bros Ultimate"],
    ["Falco", "Star Fox", "Super Smash Bros Ultimate"],
    ["Krystal", "Star Fox", "Super Smash Bros Ultimate"],
    ["Andross", "Star Fox", "Super Smash Bros Ultimate"],
    ["R2-D2", "Star Wars", "Ready Player One", "Fortnite"],
    ["Rey", "Star Wars", "Fortnite"],
    ["Finn", "Star Wars", "Fortnite"],
    ["The Mandalorian", "Star Wars", "Fortnite"],
    ["Grogu", "Star Wars", "Fortnite"],
    ["Boba Fett", "Star Wars", "Fortnite"],
    ["Fennec Shand", "Star Wars", "Fortnite"],
    ["Krrsantan", "Star Wars", "Fortnite"],
    ["Obi-Wan Kenobi", "Star Wars", "Fortnite"],
    ["Darth Vader", "Star Wars", "Fortnite"],
    ["Luke Skywalker", "Star Wars", "Fortnite"],
    ["Leia Organa", "Star Wars", "Fortnite"],
    ["Han Solo", "Star Wars", "Fortnite"],
    ["Anakin Skywalker", "Star Wars", "Fortnite"],
    ["Padme Amidala", "Star Wars", "Fortnite"],
    ["Darth Maul", "Star Wars", "Fortnite"],
    ["Ahsoka Tano", "Star Wars", "Fortnite"],
    ["Lando Calrissian", "Star Wars", "Fortnite"],
    ["Chewbacca", "Star Wars", "Fortnite"],
    ["Captain Phasma", "Star Wars", "Fortnite"],
    ["Emperor Palpatine", "Star Wars", "Fortnite"],
    ["Poe Dameron", "Star Wars", "Fortnite"],
    ["Mace Windu", "Star Wars", "Fortnite"],
    ["General Grievous", "Star Wars", "Fortnite"],
    ["Jar Jar Binks", "Star Wars", "Fortnite"],
    ["Moff Gideon", "Star Wars", "Fortnite"],
    ["Jim Raynor", "StarCraft", "Ready Player One"],
    ["Steven", "Steven Universe", "MultiVersus"],
    ["Garnet", "Steven Universe", "MultiVersus"],
    ["Chief Hopper", "Stranger Things", "Fortnite", "Magic: The Gathering"],
    ["Mind Flayer", "Stranger Things", "Magic: The Gathering"],
    ["Max", "Stranger Things", "Magic: The Gathering"],
    ["Demogorgon", "Stranger Things", "Fortnite"],
    ["Eleven", "Stranger Things", "Fortnite", "Magic: The Gathering"],
    ["Steve", "Stranger Things", "Fortnite", "Dead By Daylight"],
    ["Nancy", "Stranger Things", "Fortnite", "Dead By Daylight"],
    ["Jonathan", "Stranger Things", "Dead By Daylight"],
    ["Vecna", "Stranger Things", "Fortnite", "Dead By Daylight"],
    ["Dustin", "Stranger Things", "Fortnite", "Magic: The Gathering"],
    ["Lucas", "Stranger Things", "Fortnite"],
    ["Mike", "Stranger Things", "Fortnite", "Magic: The Gathering"],
    ["Will", "Stranger Things", "Fortnite", "Magic: The Gathering"],
    ["Chun Li", "Street Fighter", "Overwatch", "Fortnite", "Ready Player One", "Magic: The Gathering"],
    ["Ryu", "Street Fighter", "Overwatch", "Fortnite", "Ready Player One", "Super Smash Bros Ultimate", "Magic: The Gathering"],
    ["Dhalsim", "Street Fighter", "Overwatch", "Magic: The Gathering"],
    ["M. Bison", "Street Fighter", "Overwatch"],
    ["Juri", "Street Fighter", "Overwatch"],
    ["Cammy", "Street Fighter", "Overwatch", "Fortnite"],
    ["Blanka", "Street Fighter", "Overwatch", "Fortnite", "Ready Player One", "Magic: The Gathering"],
    ["Guile", "Street Fighter", "Overwatch", "Fortnite", "Super Smash Bros Ultimate", "Magic: The Gathering"],
    ["Sakura", "Street Fighter", "Fortnite"],
    ["Zangief", "Street Fighter", "Magic: The Gathering"],
    ["Ken", "Street Fighter", "Super Smash Bros Ultimate"],
    ["Sagat", "Street Fighter", "Ready Player One"],
    ["E. Honda", "Street Fighter", "Ready Player One", "Magic: The Gathering"],
    ["Super Meat Boy", "Super Meat Boy", "Fortnite"],
    ["AiAi", "Super Monkey Ball", "Sonic Racing: CrossWorlds"],
    ["Guggimon", "Superplastic", "Fortnite"],
    ["Janky", "Superplastic", "Fortnite"],
    ["Nikki", "Swapnote", "Super Smash Bros Ultimate"],
    ["Ares", "TRON", "Fortnite"],
    ["Ralph", "Teenage Muntan Ninja Turtles", "Fortnite", "Magic: The Gathering"],
    ["Leonardo", "Teenage Mutant Ninja Turtles", "Ready Player One", "Fortnite", "Sonic Racing: CrossWorlds"],
    ["Michelangelo", "Teenage Mutant Ninja Turtles", "Ready Player One", "Fortnite", "Sonic Racing: CrossWorlds"],
    ["Donatello", "Teenage Mutant Ninja Turtles", "Ready Player One", "Fortnite", "Magic: The Gathering", "Sonic Racing: CrossWorlds"],
    ["Raphael", "Teenage Mutant Ninja Turtles", "Ready Player One", "Fortnite", "Sonic Racing: CrossWorlds"],
    ["Shredder", "Teenage Mutant Ninja Turtles", "Fortnite", "Magic: The Gathering"],
    ["April Oneil", "Teenage Mutant Ninja Turtles", "Fortnite"],
    ["Baxter", "Teenage Mutant Ninja Turtles", "Fortnite", "Magic: The Gathering"],
    ["Splinter", "Teenage Mutant Ninja Turtles", "Fortnite", "Magic: The Gathering"],
    ["Krang", "Teenage Mutant Ninja Turtles", "Fortnite", "Magic: The Gathering"],
    ["Bebop", "Teenage Mutant Ninja Turtles", "Fortnite", "Magic: The Gathering"],
    ["Rocksteady", "Teenage Mutant Ninja Turtles", "Fortnite", "Magic: The Gathering"],
    ["Casey Jones", "Teenage Mutant Ninja Turtles", "Fortnite"],
    ["Ronin", "Teenage Mutant Ninja Turtles", "Magic: The Gathering"],
    ["Kazuya", "Tekken", "Super Smash Bros Ultimate"],
    ["Art the Clown", "Terrifier", "Fortnite"],
    ["Wednesday Addams", "The Addams Family", "Fortnite"],
    ["Pomni", "The Amazing Digital Circus", "Fortnite"],
    ["Jax", "The Amazing Digital Circus", "Fortnite"],
    ["Dar", "The Beastmaster", "Ready Player One"],
    ["Kiri", "The Beastmaster", "Ready Player One"],
    ["Isaac", "The Binding of Isaac", "Fortnite", "Balatro"],
    ["Mother", "The Binding of Isaac", "Balatro"],
    ["Duke of Flies", "The Binding of Isaac", "Fortnite"],
    ["The Grabber", "The Black Phone", "Fortnite"],
    ["John Bender", "The Breakfast Club", "Ready Player One"],
    ["Mr. Incredible", "The Incredibles", "Fortnite"],
    ["Frozone", "The Incredibles", "Fortnite"],
    ["Mrs. Incredible", "The Incredibles", "Fortnite"],
    ["The Iron Giant", "The Iron Giant", "Ready Player One", "MultiVersus"],
    ["Hogarth Hughes", "The Iron Giant"],
    ["Ellie", "The Last of Us", "Magic: The Gathering"],
    ["Joel", "The Last of Us", "Magic: The Gathering"],
    ["Abby", "The Last of Us", "Magic: The Gathering"],
    ["Link", "The Legend of Zelda", "Super Smash Bros Ultimate"],
    ["Shiek", "The Legend of Zelda", "Super Smash Bros Ultimate"],
    ["Zelda", "The Legend of Zelda", "Super Smash Bros Ultimate"],
    ["Girahim", "The Legend of Zelda", "Super Smash Bros Ultimate"],
    ["Midna", "The Legend of Zelda", "Super Smash Bros Ultimate"],
    ["Moon", "The Legend of Zelda", "Super Smash Bros Ultimate"],
    ["Skull Kid", "The Legend of Zelda", "Super Smash Bros Ultimate"],
    ["Ganondorf", "The Legend of Zelda", "Super Smash Bros Ultimate"],
    ["Starfy", "The Legendary Starfy", "Super Smash Bros Ultimate"],
    ["Gandalf", "The Lord of the Rings", "Ready Player One", "MultiVersus", "Magic: The Gathering"],
    ["Sauron", "The Lord of the Rings"],
    ["Galadriel", "The Lord of the Rings", "Magic: The Gathering"],
    ["Grima Wormtongue", "The Lord of the Rings", "Magic: The Gathering"],
    ["Aragorn", "The Lord of the Rings"],
    ["Frodo", "The Lord of the Rings"],
    ["Legolas", "The Lord of the Rings"],
    ["Gollum", "The Lord of the Rings"],
    ["Agent Smith", "The Matrix", "MultiVersus"],
    ["Agent Jones", "The Matrix", "MultiVersus"],
    ["Agent Brown", "The Matrix", "MultiVersus"],
    ["Mummy", "The Mummy", "Fortnite"],
    ["Kermit The Frog", "The Muppets", "Ready Player One"],
    ["Ms. Piggy", "The Muppets", "Ready Player One"],
    ["Takamaru", "The Mysterious Murasame Castle", "Super Smash Bros Ultimate"],
    ["Jack Skellington", "The Nightmare Before Christmas", "Fortnite", "Disney Dreamlight Valley"],
    ["Sally", "The Nightmare Before Christmas", "Fortnite", "Disney Dreamlight Valley"],
    ["Michael Scott", "The Office", "Fortnite"],
    ["Dwight Scrute", "The Office", "Fortnite", "Magic: The Gathering"],
    ["The Predator", "The Predator", "Fortnite"],
    ["Princess Buttercup", "The Princess Bride", "Magic: The Gathering"],
    ["Vizzini", "The Princess Bride", "Magic: The Gathering"],
    ["Vestli", "The Princess Bride", "Magic: The Gathering"],
    ["Fezzik", "The Princess Bride", "Magic: The Gathering"],
    ["Inigo Montoya", "The Princess Bride", "Magic: The Gathering"],
    ["Miracle Max", "The Princess Bride", "Magic: The Gathering"],
    ["Jack Torrance", "The Shining", "Ready Player One"],
    ["Alexa Grady", "The Shining", "Ready Player One"],
    ["Alexie Grady", "The Shining", "Ready Player One"],
    ["Lorraine Massey ", "The Shining", "Ready Player One"],
    ["Homer Simpson", "The Simpsons", "Fortnite"],
    ["Ned Flanders", "The Simpsons", "Fortnite"],
    ["Marge Simpson", "The Simpsons", "Fortnite"],
    ["Bart Simpson", "The Simpsons", "Fortnite"],
    ["Krusty the Clown", "The Simpsons", "Fortnite"],
    ["Moe Szyslak", "The Simpsons", "Fortnite"],
    ["Lisa Simpson", "The Simpsons", "Fortnite"],
    ["Scratchy", "The Simpsons", "Fortnite"],
    ["Itchy", "The Simpsons", "Fortnite"],
    ["KPlopper", "The Simpsons", "Fortnite"],
    ["Sarah Connor", "The Terminator", "Fortnite"],
    ["T-800", "The Terminator", "Fortnite"],
    ["Leatherface", "The Texas Chainsaw Massacre", "Fortnite", "Dead By Daylight"],
    ["Daryl Dixon", "The Walking Dead", "Fortnite", "Magic: The Gathering"],
    ["Michonne", "The Walking Dead", "Fortnite", "Magic: The Gathering"],
    ["Rick Grimes", "The Walking Dead", "Fortnite", "Magic: The Gathering"],
    ["Glenn Rhee", "The Walking Dead", "Magic: The Gathering"],
    ["Negan", "The Walking Dead", "Fortnite", "Magic: The Gathering"],
    ["Geralt of Rivia", "The Witcher", "Fortnite", "Balatro"],
    ["Dandelion", "The Witcher", "Balatro"],
    ["Ciri", "The Witcher", "Fortnite"],
    ["Yennefer", "The Witcher", "Fortnite", "Balatro"],
    ["Larry Talbot", "The Wolf Man", "Ready Player One"],
    ["Ken Kaneki", "Tokyo Ghoul", "Dead By Daylight"],
    ["Rize Kamishiro", "Tokyo Ghoul", "Dead By Daylight"],
    ["Tom", "Tom & Jerry", "MultiVersus"],
    ["Jerry", "Tom & Jerry", "MultiVersus"],
    ["Lara Croft", "Tomb Raider", "Ready Player One", "Fortnite", "Dead By Daylight", "Magic: The Gathering"],
    ["Buzz Lightyear", "Toy Story", "Fortnite", "Disney Dreamlight Valley"],
    ["Woody", "Toy Story", "Disney Dreamlight Valley"],
    ["Emperor Zurg", "Toy Story", "Fortnite"],
    ["Alien", "Toy Story", "Fortnite"],
    ["Optimus Prime", "Transformers", "Overwatch", "Fortnite", "Ready Player One", "Magic: The Gathering"],
    ["Bumblebee", "Transformers", "Overwatch", "Fortnite"],
    ["Megatron", "Transformers", "Overwatch", "Ready Player One", "Fortnite", "Magic: The Gathering"],
    ["Starscream", "Transformers"],
    ["Soundwave", "Transformers"],
    ["Ironhide", "Transformers"],
    ["Ratchet", "Transformers"],
    ["Wheeljack", "Transformers"],
    ["Grimlock", "Transformers"],
    ["Shockwave", "Transformers"],
    ["Arcee", "Transformers", "Overwatch"],
    ["Optimus Primal", "Transformers", "Fortnite"],
    ["Nathan Drake", "Uncharted", "Fortnite", "Magic: The Gathering"],
    ["Chloe Frazer", "Uncharted", "Fortnite", "Magic: The Gathering"],
    ["Garog", "Unreal Tournament", "Fortnite"],
    ["Samael", "Unreal Tournament", "Fortnite"],
    ["Akira", "Virtua Fighters", "Super Smash Bros Ultimate"],
    ["Hatsune Miku", "Vocaloid", "Fortnite", "Magic: The Gathering", "Sonic Racing: CrossWorlds"],
    ["David Lightman", "WarGames", "Ready Player One"],
    ["Jennifer Mack", "WarGames", "Ready Player One"],
    ["Excalibur", "Warframe", "Fortnite", "Balatro"],
    ["Volt", "Warframe", "Balatro"],
    ["Mag", "Warframe", "Balatro"],
    ["Badrukk", "Warhammer 40K", "Magic: The Gathering"],
    ["Makari", "Warhammer 40K", "Magic: The Gathering"],
    ["Nagash", "Warhammer 40K", "Magic: The Gathering"],
    ["Ghazghkull Thraka", "Warhammer 40K", "Magic: The Gathering"],
    ["Neave Blacktalon", "Warhammer 40K", "Magic: The Gathering"],
    ["Archaon", "Warhammer 40K", "Magic: The Gathering"],
    ["Stardrake", "Warhammer 40K", "Magic: The Gathering"],
    ["Ghal Maraz", "Warhammer 40K", "Magic: The Gathering"],
    ["Wii Fit Trainer", "Wii", "Super Smash Bros Ultimate"],
    ["Mii Character", "Wii", "Super Smash Bros Ultimate"],
    ["Lich King", "World of Warcraft", "Overwatch"],
    ["Sylvanas", "World of Warcraft", "Overwatch"],
    ["Thrall", "World of Warcraft", "Overwatch"],
    ["Diamond Magni", "World of Warcraft", "Overwatch"],
    ["Pepe", "World of Warcraft", "Overwatch"],
    ["Wreck-It Ralph", "Wreck-It Ralph", "Fortnite", "Disney Dreamlight Valley"],
    ["Venelope", "Wreck-It Ralph", "Fortnite"], "Disney Dreamlight Valley",
    ["Sheik", "Xenoblade Chronicles", "Super Smash Bros Ultimate"],
    ["Pyra", "Xenoblade Chronicles", "Super Smash Bros Ultimate"],
    ["Mythra", "Xenoblade Chronicles", "Super Smash Bros Ultimate"],
    ["Riki", "Xenoblade Chronicles", "Super Smash Bros Ultimate"],
    ["Akari Hayami", "1080 Degrees", "Super Smash Bros Ultimate"],
    ["Andy", "Advance Wars", "Super Smash Bros Ultimate"],
    ["Eagle", "Advance Wars", "Super Smash Bros Ultimate"],
    ["Olaf", "Advance Wars", "Super Smash Bros Ultimate"],
    ["Tom Nook", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Timmy", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Tommy", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["K.K. Slider", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Resetti", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Don", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Rover", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Redd", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Gracie", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Gulliver", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Pete", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Phylis", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Pelly", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Copper", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Booker", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Joan", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Katrina", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Lloid", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Tortimer", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Mable", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Lable", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Sable", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Blathers", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Celeste", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Harriet", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Brewster", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Lyle", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Kaitlin", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Katie", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Dr. Shrunk", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Frilliard", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Kicks", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Zipper T. Bunny", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Serena", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Cyrus", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Reese", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Leif", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Digby", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Lottie", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Orville", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Wilbur", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["C.J.", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Flick", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Daisy Mae", "Animal Crossing", "Super Smash Bros Ultimate"],
    ["Ryo Sakazaki", "Art of Fighting", "Super Smash Bros Ultimate"],
    ["Aisya", "Super Smash Bros Ultimate", "ASH: Archaic Sealed Heat"],
    ["Kyle", "ASTRAL CHAIN", "Super Smash Bros Ultimate"],
    ["Lappy", "ASTRAL CHAIN", "Super Smash Bros Ultimate"],
    ["Balloon Fighter", "Balloon Fight", "Super Smash Bros Ultimate"],
    ["Fish", "Balloon Fight", "Super Smash Bros Ultimate"],
    ["Sagi", "Beaten Kaitos", "Super Smash Bros Ultimate"],
    ["Milly", "Beaten Kaitos", "Super Smash Bros Ultimate"],
    ["Dr. Lobe", "Big Brain Academy", "Super Smash Bros Ultimate"],
    ["Qbby", "BOXBOY!", "Super Smash Bros Ultimate"],
    ["Dr. Kawashima", "Brain Age", "Super Smash Bros Ultimate"],
    ["Seth", "Bravely Default", "Super Smash Bros Ultimate"],
    ["Gloria", "Bravely Default", "Super Smash Bros Ultimate"],
    ["Elvis", "Bravely Default", "Super Smash Bros Ultimate"],
    ["Adelle", "Bravely Default", "Super Smash Bros Ultimate"],
    ["Nick", "Captain Rainbow", "Super Smash Bros Ultimate"],
    ["Captain Rainbow", "Captain Rainbow", "Super Smash Bros Ultimate"],
    ["Chibi Robo", "Chibi Robo", "Super Smash Bros Ultimate"],
    ["Telly", "Chibi Robo", "Super Smash Bros Ultimate"],
    ["Drake Redcrest", "Chibi Robo", "Super Smash Bros Ultimate"],
    ["Chibi-Tot", "Chibi Robo", "Super Smash Bros Ultimate"],
    ["Warrior Mech Gauss", "Chou Soujuu Meka MG", "Super Smash Bros Ultimate"],
    ["Bubbles", "Clu Clu Land", "Super Smash Bros Ultimate"],
    ["Unira", "Clu Clu Land", "Super Smash Bros Ultimate"],
    ["Henry Fleming", "Code Name: S.T.E.A.M.", "Super Smash Bros Ultimate"],
    ["Pig", "Cubivore: Survival of the Fittest", "Super Smash Bros Ultimate"],
    ["Culdra", "Culdcept", "Super Smash Bros Ultimate"],
    ["Goligan", "Culdcept", "Super Smash Bros Ultimate"],
    ["Allen", "Culdcept", "Super Smash Bros Ultimate"],
    ["Cuphead", "Cuphead", "Super Smash Bros Ultimate"],
    ["Mugman", "Cuphead", "Super Smash Bros Ultimate"],
    ["The Devil", "Cuphead", "Super Smash Bros Ultimate"],
    ["King Dice", "Cuphead", "Super Smash Bros Ultimate"],
    ["Ray Mk II", "Custom Robo", "Super Smash Bros Ultimate"],
    ["Ray Mk III", "Custom Robo", "Super Smash Bros Ultimate"],
    ["Flare", "Custom Robo", "Super Smash Bros Ultimate"],
    ["Bayonette", "Custom Robo", "Super Smash Bros Ultimate"],
    ["Aladdin", "Aladdin", "Disney Dreamlight Valley"],
    ["Jafar", "Aladdin", "Disney Dreamlight Valley"],
    ["Jasmine", "Aladdin", "Disney Dreamlight Valley"],
    ["Alice", "Alice in Wonderland", "Disney Dreamlight Valley"],
    ["Cheshire Cat", "Alice in Wonderland", "Disney Dreamlight Valley"],
    ["Belle", "Beauty and the Beast", "Disney Dreamlight Valley"],
    ["Gaston", "Beauty and the Beast", "Disney Dreamlight Valley"],
    ["The Beast", "Beauty and the Beast", "Disney Dreamlight Valley"],
    ["Lumiere", "Beauty and the Beast", "Disney Dreamlight Valley"],
    ["Cogsworth", "Beauty and the Beast", "Disney Dreamlight Valley"],
    ["Cinderella", "Cinderella", "Disney Dreamlight Valley"],
    ["The Fairy Godmother", "Cinderella", "Disney Dreamlight Valley"],
    ["The Forgotten", "Disney Dreamlight Valley"],
    ["Mirabel", "Encanto", "Disney Dreamlight Valley"],
    ["Anna", "Frozen", "Disney Dreamlight Valley"],
    ["Elsa", "Frozen", "Disney Dreamlight Valley"],
    ["Kristoff", "Frozen", "Disney Dreamlight Valley"],
    ["Olaf", "Frozen", "Disney Dreamlight Valley"],
    ["Joy", "Inside Out", "Disney Dreamlight Valley"],
    ["Sadness", "Inside Out", "Disney Dreamlight Valley"],
    ["Lady", "Lady and the Tramp", "Disney Dreamlight Valley"],
    ["Tramp", "Lady and the Tramp", "Disney Dreamlight Valley"],
    ["Stitch", "Lilo and Stitch", "Disney Dreamlight Valley"],
    ["Lilo", "Lilo and Stitch"],
    ["Maui", "Moana", "Disney Dreamlight Valley"],
    ["Moana", "Moana", "Disney Dreamlight Valley"],
    ["Mike Wazowski", "Monsters Inc.", "Disney Dreamlight Valley"],
    ["Sully", "Monsters Inc.", "Disney Dreamlight Valley"],
    ["Mulan", "Mulan", "Disney Dreamlight Valley"],
    ["Mushu", "Mulan", "Disney Dreamlight Valley"],
    ["Peter Pan", "Peter Pan", "Disney Dreamlight Valley"],
    ["Pocahontas", "Pocahontas", "Disney Dreamlight Valley"],
    ["Remy", "Ratatuille", "Disney Dreamlight Valley"],
    ["Mother Gothel", "Tangled", "Disney Dreamlight Valley"],
    ["Rapunzel", "Tangled", "Disney Dreamlight Valley"],
    ["Timon", "The Lion King", "Disney Dreamlight Valley"],
    ["Pumba", "The Lion King", "Disney Dreamlight Valley"],
    ["Scar", "The Lion King", "Disney Dreamlight Valley"],
    ["Simba", "The Lion King", "Disney Dreamlight Valley"],
    ["Nala", "The Lion King", "Disney Dreamlight Valley"],
    ["Ariel", "The Little Mermaid", "Disney Dreamlight Valley"],
    ["Prince Erik", "The Little Mermaid", "Disney Dreamlight Valley"],
    ["Ursula", "The Little Mermaid", "Disney Dreamlight Valley"],
    ["Tiana", "The Princess and the Frog", "Disney Dreamlight Valley"],
    ["Merlin", "The Sword in the Stone", "Disney Dreamlight Valley"],
    ["WALL-E", "WALL-E", "Disney Dreamlight Valley"],
    ["EVE", "WALL-E", "Disney Dreamlight Valley"],
    ["Oswald", "Oswald the Lucky Rabbit", "Disney Dreamlight Valley"],
    ["Merida", "Brave", "Disney Dreamlight Valley"],
    ["Aurora", "Sleeping Beauty", "Disney Dreamlight Valley"],
    ["Tinker Bell", "Peter Pan", "Disney Dreamlight Valley"],
    ["Snow White", "Snow White", "Disney Dreamlight Valley"],
    ["Tigger", "Winnie the Pooh", "Disney Dreamlight Valley"],
    ["Eeyore", "Winnie the Pooh", "Disney Dreamlight Valley"],
    ["Piglet", "Winnie the Pooh", "Disney Dreamlight Valley"],
    ["Winnie the Pooh", "Winnie the Pooh", "Disney Dreamlight Valley"],
    ["Jimbo", "Balatro", "Slay the Spire"],
    ["Principal", "1000xResist", "Balatro"],
    ["Allmother", "1000xResist", "Balatro"],
    ["Watcher", "1000xResist", "Balatro"],
    ["Mushroomist", "Potion Craft", "Balatro"],
    ["Herbalist", "Potion Craft", "Balatro"],
    ["Alchemist", "Potion Craft", "Balatro"],
    ["Wilson", "Dont Starve", "Balatro"],
    ["Charlie", "Dont Starve", "Balatro"],
    ["Maxwell", "Dont Starve", "Balatro"],
    ["Poe Ratcho", "Vampire Survivors", "Balatro"],
    ["Queen Sigma", "Vampire Survivors", "Balatro"],
    ["Lamb", "Cult of the Lamb", "Balatro"],
    ["Goat", "Cult of the Lamb", "Balatro"],
    ["Ratau", "Cult of the Lamb", "Balatro"],
    ["Fane", "Original Sin", "Balatro"],
    ["Lohse", "Original Sin", "Balatro"],
    ["The Red Prince", "Original Sin", "Balatro"],
    ["The Shield Knight", "Shovel Knight", "Balatro"],
    ["The Shovel Knight", "Shovel Knight", "Balatro"],
    ["The Enchantress", "Shovel Knight", "Balatro"],
    ["The Defect", "Slay the Spire", "Balatro"],
    ["Silent", "Slay the Spire", "Balatro"],
    ["The Ironclad Soldier", "Slay the Spire", "Balatro"],
    ["Pierre", "Stardew Valley", "Balatro"],
    ["Marnie", "Stardew Valley", "Balatro"],
    ["Lewis", "Stardew Valley", "Balatro"],
    ["Radiant Gleam", "DAEMON X MACHINA", "Super Smash Bros Ultimate"],
    ["Kloster", "DAEMON X MACHINA", "Super Smash Bros Ultimate"],
    ["Bullet Walker", "DAEMON X MACHINA", "Super Smash Bros Ultimate"],
    ["High Lines", "DAEMON X MACHINA", "Super Smash Bros Ultimate"],
    ["Inuji Darumeshi", "Darumeshi Sports Store", "Super Smash Bros Ultimate"],
    ["Dillon", "Dillon's Dead-Heat Breakers", "Super Smash Bros Ultimate"],
    ["Russ", "Dillon's Dead-Heat Breakers", "Super Smash Bros Ultimate"],
    ["Raymond Bryce", "Disaster: Day of Crisis", "Super Smash Bros Ultimate"],
    ["Diskun", "Disk System", "Super Smash Bros Ultimate"],
    ["Karate Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Ninja Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Lady", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Cranky Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Funky Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Candy Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Swanky Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Wrinkly Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Dixie Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Kiddie Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Lanky Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Tiny Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Chunky Kong", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Stanley", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Rambi", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Enguarde", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Squawks", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Expresso", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Winky", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Squitter", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Rattly", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Ellie", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Professor Chops", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Kritter", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Zinger", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Klaptrap", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Kaptain K. Rool", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Baron K. Roolstein", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Blast-o-Matic", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Lord Frederik", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Kip", "Donkey Kong", "Super Smash Bros Ultimate"],
    ["Kalypso", "Donkey Kong", "Super Smash Bros Ultimate"],


    
    
    
]
def pretty():
    with open("um.txt", "w") as f:
        f.write(sorted(characters, key=lambda x:x[1]).__str__())