
import json
new_characters = [ 
        ["Beast", "Beauty and the Beast", "Disney Speedstorm"],
        ["Belle", "Beauty and the Beast", "Disney Speedstorm"],
        ["Gaston", "Beauty and the Beast", "Disney Speedstorm"],
        ["Hades", "Disney's Hercules", "Disney Speedstorm"],
        ["Hercules", "Disney's Hercules", "Disney Speedstorm"],
        ["Meg", "Disney's Hercules", "Disney Speedstorm"],
        ["Daisy", "Mickey and Friends", "Disney Speedstorm"],
        ["Donald Duck", "Mickey and Friends", "Disney Speedstorm"],
        ["Goofy", "Mickey and Friends", "Disney Speedstorm"],
        ["Mickey Mouse", "Mickey and Friends", "Disney Speedstorm"],
        ["Minnie Mouse", "Mickey and Friends", "Disney Speedstorm"],
        ["Pete", "Mickey and Friends", "Disney Speedstorm"],
        ["Chip", "Mickey and Friends", "Disney Speedstorm"],
        ["Dale", "Mickey and Friends", "Disney Speedstorm"],
        ["Scrooge McDuck", "Mickey and Friends", "Disney Speedstorm"],
        ["Mulan", "Mulan", "Disney Speedstorm"],
        ["Shan Yu", "Mulan", "Disney Speedstorm"],
        ["Shang", "Mulan", "Disney Speedstorm"],
        ["Captain Barbossa", "Pirates of the Caribbean", "Disney Speedstorm"],
        ["Davy Jones", "Pirates of the Caribbean", "Disney Speedstorm"],
        ["Elizabeth Swann", "Pirates of the Caribbean", "Disney Speedstorm"],
        ["Jack Sparrow", "Pirates of the Caribbean", "Disney Speedstorm"],
        ["Tia Dalma", "Pirates of the Caribbean", "Disney Speedstorm"],
        ["Will Turner", "Pirates of the Caribbean", "Disney Speedstorm"],
        ["Mowgli", "The Jungle Book", "Disney Speedstorm"],
        ["Baloo", "The Jungle Book", "Disney Speedstorm"],
        ["Mike", "Monsters Inc.", "Disney Speedstorm"],
        ["Sulley", "Monsters Inc.", "Disney Speedstorm"],
        ["Randall", "Monsters Inc.", "Disney Speedstorm"],
        ["Celia Mae", "Monsters Inc.", "Disney Speedstorm"],
        ["Bo Peep", "Toy Story", "Disney Speedstorm"],
        ["Buzz Lightyear", "Toy Story", "Disney Speedstorm"],
        ["Emperor Zurg", "Toy Story", "Disney Speedstorm"],
        ["Forky", "Toy Story", "Disney Speedstorm"],
        ["Jessie", "Toy Story", "Disney Speedstorm"],
        ["Lotso", "Toy Story", "Disney Speedstorm"],
        ["Rex", "Toy Story", "Disney Speedstorm"],
        ["Woody", "Toy Story", "Disney Speedstorm"],
        ["Angel", "Lilo and Stitch", "Disney Speedstorm"],
        ["Gantu", "Lilo and Stitch", "Disney Speedstorm"],
        ["Jumba", "Lilo and Stitch", "Disney Speedstorm"],
        ["Lilo", "Lilo and Stitch", "Disney Speedstorm"],
        ["Stitch", "Lilo and Stitch", "Disney Speedstorm"],
        ["Aladdin", "Aladdin", "Disney Speedstorm"],
        ["Genie", "Aladdin", "Disney Speedstorm"],
        ["Jafar", "Aladdin", "Disney Speedstorm"],
        ["Jasmine", "Aladdin", "Disney Speedstorm"],
        ["Anna", "Frozen", "Disney Speedstorm"],
        ["Elsa", "Frozen", "Disney Speedstorm"],
        ["Hans", "Frozen", "Disney Speedstorm"],
        ["Kristoff", "Frozen", "Disney Speedstorm"],
        ["Olaf", "Frozen", "Disney Speedstorm"],
        ["Oswald", "Oswald the Lucky Rabbit", "Disney Speedstorm"],
        ["Ortensia", "Oswald the Lucky Rabbit", "Disney Speedstorm"],
        ["WALL-E", "WALL-E", "Disney Speedstorm"],
        ["EVE", "WALL-E", "Disney Speedstorm"],
        ["Ariel", "The Little Mermaid", "Disney Speedstorm"],
        ["King Triton", "The Little Mermaid", "Disney Speedstorm"],
        ["Prince Eric", "The Little Mermaid", "Disney Speedstorm"],
        ["Ursula", "The Little Mermaid", "Disney Speedstorm"],
        ["Wreck-It Ralph", "Wreck-It Ralph", "Disney Speedstorm"],
        ["Venellope", "Wreck-It Ralph", "Disney Speedstorm"],
        ["King Candy", "Wreck-It Ralph", "Disney Speedstorm"],
        ["Fix-It Felix", "Wreck-It Ralph", "Disney Speedstorm"],
        ["Fozzie Bear", "The Muppets", "Disney Speedstorm"],
        ["Kermit the Frog", "The Muppets", "Disney Speedstorm"],
        ["Miss Piggy", "The Muppets", "Disney Speedstorm"],
        ["Anger", "Inside Out", "Disney Speedstorm"],
        ["Anxiety", "Inside Out", "Disney Speedstorm"],
        ["Disgust", "Inside Out", "Disney Speedstorm"],
        ["Ennui", "Inside Out", "Disney Speedstorm"],
        ["Fear", "Inside Out", "Disney Speedstorm"],
        ["Joy", "Inside Out", "Disney Speedstorm"],
        ["Sadness", "Inside Out", "Disney Speedstorm"],
        ["Cruella De Vil", "101 Dalmatians", "Disney Speedstorm"],
        ["Aurora", "Sleeping Beauty", "Disney Speedstorm"],
        ["Maleficent", "Sleeping Beauty", "Disney Speedstorm"],
        ["Dr. Finkelstein", "The Nightmare Before Christmas", "Disney Speedstorm"],
        ["Sally", "The Nightmare Before Christmas", "Disney Speedstorm"],
        ["Jack Skellington", "The Nightmare Before Christmas", "Disney Speedstorm"],
        ["Oogie Boogie", "The Nightmare Before Christmas", "Disney Speedstorm"],
        ["Mother Gothel", "Tangled", "Disney Speedstorm"],
        ["Repunzel", "Tangled", "Disney Speedstorm"],
        ["Dash", "The Incredibles", "Disney Speedstorm"],
        ["Frozone", "The Incredibles", "Disney Speedstorm"],
        ["Mrs. Incredible", "The Incredibles", "Disney Speedstorm"],
        ["Mr. Incredible", "The Incredibles", "Disney Speedstorm"],
        ["Syndrome", "The Incredibles", "Disney Speedstorm"],
        ["Violet", "The Incredibles", "Disney Speedstorm"],
        ["Moana", "Moana", "Disney Speedstorm"],
        ["Maui", "Moana", "Disney Speedstorm"],
        ["Quorra", "TRON", "Disney Speedstorm"],
        ["Rinzler", "TRON", "Disney Speedstorm"],
        ["Sam", "TRON", "Disney Speedstorm"],
        ["Zuse", "TRON", "Disney Speedstorm"],
        ["Snow White", "Snow White", "Disney Speedstorm"],
        ["The Evil Queen", "Snow White", "Disney Speedstorm"],
        ["Baymax", "Big Hero 6", "Disney Speedstorm"],
        ["Go Go", "Big Hero 6", "Disney Speedstorm"],
        ["Hiro", "Big Hero 6", "Disney Speedstorm"],
        ["Honey Lemon", "Big Hero 6", "Disney Speedstorm"],
        ["Yokai", "Big Hero 6", "Disney Speedstorm"],
        ["Cinderella", "Cinderella", "Disney Speedstorm"],
        ["Alice", "Alice in Wonderland", "Disney Speedstorm"],
        ["Mad Hatter", "Alice in Wonderland", "Disney Speedstorm"],
        ["Queen of Hearts", "Alice in Wonderland", "Disney Speedstorm"],
        ["Winnie the Pooh", "Winnie the Pooh", "Disney Speedstorm"],
        ["Eeyore", "Winnie the Pooh", "Disney Speedstorm"],
        ["Tigger", "Winnie the Pooh", "Disney Speedstorm"],
        ["Russel", "Up", "Disney Speedstorm"],
        ["Carl", "Up", "Disney Speedstorm"],
        ["Flash", "Zootopia", "Disney Speedstorm"],
        ["Judy Hopps", "Zootopia", "Disney Speedstorm"],
        ["Nick Wilde", "Zootopia", "Disney Speedstorm"],
        ["Kuzco", "The Emperor's New Groove", "Disney Speedstorm"],
        ["Yzma", "The Emperor's New Groove", "Disney Speedstorm"],
        ["Mater", "Cars", "Disney Speedstorm"],
        ["Cruz", "Cars", "Disney Speedstorm"],
        ["Lightning McQueen", "Cars", "Disney Speedstorm"],
        ["Mabel", "Hoppers", "Disney Speedstorm"],
        ["Captain Hook", "Peter Pan", "Disney Speedstorm"],
        ["Peter Pan", "Peter Pan", "Disney Speedstorm"],
        ["Tinker Pan", "Peter Pan", "Disney Speedstorm"],
        ["Merida", "Brave", "Disney Speedstorm"],
        ["Isabela", "Encanto", "Disney Speedstorm"],
        ["Luisa", "Encanto", "Disney Speedstorm"],
        ["Mirabel", "Encanto", "Disney Speedstorm"],
]

def add_characters():
    with open("character.json", "r") as f:
        char_json = json.load(f) #type: list[dict]
    for i in new_characters:
            if i[0] in [j["name"] for j in char_json if j["name"]==i[0] and j["origin"] == i[1]]:
                 print(i[0], "from", i[1], "is already in, adding new groups")
                 new_dict = char_json.pop(char_json.index([j for j in char_json if j["name"]==i[0] and j["origin"] == i[1]][0]))
                 new_groups = new_dict["groups"] + i[1:]
                 new_groups = list(set(new_groups))
                 new_dict["groups"] = new_groups
                 char_json.append(new_dict)
            else:
                new_dict = {"name": i[0], "origin": i[1], "groups": i[1:]}
                char_json.append(new_dict)
    with open("character.json", "w") as f:
        char_json.sort(key = lambda x: x["origin"]+x["name"])
        json.dump(char_json, f, indent=4)
    print("charcters added")
def characters():
    with open("character.json", "r") as f:
        return json.load(f)



add_characters()