
import json
new_characters = [ 
    ["SpongeBob SquarePants", "SpongeBob SquarePants", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl 4", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Patrick", "SpongeBob SquarePants", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2", "Nickelodeon Super Brawl 4", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Squidward", "SpongeBob SquarePants", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl 2"],
    ["Mr. Krabs", "SpongeBob SquarePants", "Nickelodeon Super Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Mrs. Puff", "SpongeBob SquarePants", "Nickelodeon All-Star Brawl 2"],
    ["Karen", "SpongeBob SquarePants", "Nickelodeon All-Star Brawl 2"],
    ["Sandy", "SpongeBob SquarePants", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2", "Nickelodeon Super Brawl Universe"],
    ["Plankton", "SpongeBob SquarePants", "Nickelodeon Super Brawl 2", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl 4", "Nickelodeon All-Star Brawl 2"],
    ["Timmy", "Fairly OddParents", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl 4", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe"],
    ["Pearl", "SpongeBob SquarePants", "Nickelodeon Super Brawl World"],
    ["Flying Dutchman", "SpongeBob SquarePants", "Nickelodeon Super Brawl World", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Gary", "SpongeBob SquarePants", "Nickelodeon All-Star Brawl"],
    ["Cosmo", "Fairly OddParents", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl World"],
    ["Wanda", "Fairly OddParents", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl World"],
    ["Poof", "Fairly OddParents", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl World"],
    ["Jorgen", "Fairly OddParents", "Nickelodeon Super Brawl"],
    ["Mr. Crocker", "Fairly OddParents", "Nickelodeon Super Brawl"],
    ["Otis", "Back at the Barnyard", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2"],
    ["Abby", "Back at the Barnyard", "Nickelodeon Super Brawl"],
    ["Pip", "Back at the Barnyard", "Nickelodeon Super Brawl"],
    ["Fanboy", "Fanboy and Chum Chum", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2"],
    ["Chum Chum", "Fanboy and Chum Chum", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2"],
    ["Boog", "Fanboy and Chum Chum", "Nickelodeon Super Brawl"],
    ["Yo", "Fanboy and Chum Chum", "Nickelodeon Super Brawl"],
    ["Kyle", "Fanboy and Chum Chum", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2"],
    ["Oz", "Fanboy and Chum Chum", "Nickelodeon Super Brawl"],
    ["Danny Phantom", "Danny Phantom", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Sam Manson", "Danny Phantom", "Nickelodeon Super Brawl"],
    ["Tucker Foley", "Danny Phantom", "Nickelodeon Super Brawl"],
    ["Vlad Plasmius", "Danny Phantom", "Nickelodeon All-Star Brawl 2"],
    ["Clockwork", "Danny Phantom", "Nickelodeon All-Star Brawl 2"],
    ["Aang", "Avatar: The Last Airbender", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Sokka", "Avatar: The Last Airbender", "Nickelodeon Super Brawl"],
    ["Korra", "Avatar: The Last Airbender", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl 4", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Tahno", "Avatar: The Last Airbender", "Nickelodeon Super Brawl 3"],
    ["Amon", "Avatar: The Last Airbender", "Nickelodeon Super Brawl 3"],
    ["Katara", "Avatar: The Last Airbender", "Nickelodeon Super Brawl"],
    ["Appa", "Avatar: The Last Airbender", "Nickelodeon Super Brawl"],
    ["Bessie", "The Mighty B!", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2"],
    ["Penny Lefcowitz", "The Mighty B!", "Nickelodeon Super Brawl"],
    ["Happy Higgenbottom", "The Mighty B!", "Nickelodeon Super Brawl"],
    ["Sheen", "Jimmy Neutron: Boy Genius", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2", "Nickelodeon All-Star Brawl 2"],
    ["Jimmy Neutron", "Jimmy Neutron: Boy Genius", "Nickelodeon Super Brawl 2", "Nickelodeon All-Star Brawl 2"],
    ["Goddard", "Jimmy Neutron: Boy Genius", "Nickelodeon All-Star Brawl 2"],
    ["Cindy", "Jimmy Neutron: Boy Genius", "Nickelodeon All-Star Brawl 2"],
    ["Carl", "Jimmy Neutron: Boy Genius", "Nickelodeon All-Star Brawl 2"],
    ["Bones", "Jimmy Neutron: Boy Genius", "Nickelodeon Super Brawl"],
    ["Hugh Neutron", "Jimmy Neutron: Boy Genius", "Nickelodeon All-Star Brawl"],
    ["Rico", "Madagascar", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2"],
    ["King Julien", "Madagascar", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2"],
    ["Dr. Blowhole", "Madagascar", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2"],
    ["Skipper", "Madagascar", "Nickelodeon Super Brawl", "Nickelodeon Super Brawl 2"],
    ["Kowalski", "Madagascar", "Nickelodeon Super Brawl"],
    ["Private", "Madagascar", "Nickelodeon Super Brawl"],
    ["Maurice", "Madagascar", "Nickelodeon Super Brawl"],
    ["Mort", "Madagascar", "Nickelodeon Super Brawl"],
    ["Dudley Puppy", "T.U.F.F. Puppy", "Nickelodeon Super Brawl 2"],
    ["Kitty Katswell", "T.U.F.F. Puppy", "Nickelodeon Super Brawl 2"],
    ["Monkey", "Monkey Quest", "Nickelodeon Super Brawl 2"],
    ["Leo", "Teenage Muntant Ninja Turtles", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl 4", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Donnie", "Teenage Muntant Ninja Turtles", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl 4", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl 2"],
    ["Raph", "Teenage Muntant Ninja Turtles", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl 4", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl 2"],
    ["Mikey", "Teenage Muntant Ninja Turtles", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl 4", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Shredder", "Teenage Muntant Ninja Turtles", "Nickelodeon Super Brawl 3", "Nickelodeon All-Star Brawl 2"],
    ["April Oneil", "Teenage Muntant Ninja Turtles", "Nickelodeon Super Brawl World", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Shinigami", "Teenage Muntant Ninja Turtles", "Nickelodeon Super Brawl World"],
    ["Kraang", "Teenage Muntant Ninja Turtles", "Nickelodeon All-Star Brawl 2"],
    ["Craig", "Sanjay and Craig", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl 4"],
    ["Sunjay", "Sanjay and Craig", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl 4"],
    ["Tufflips", "Sanjay and Craig", "Nickelodeon Super Brawl 3"],
    ["Noodman", "Sanjay and Craig", "Nickelodeon Super Brawl 3"],
    ["SwaySway", "Breadwinners", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl 4"],
    ["Buhdeuce", "Breadwinners", "Nickelodeon Super Brawl 3", "Nickelodeon Super Brawl 4"],
    ["Bloom", "Winx", "Nickelodeon Super Brawl 3"],
    ["Po", "Kung Fu Panda", "Nickelodeon Super Brawl 3"],
    ["Master Junjie", "Kung Fu Panda", "Nickelodeon Super Brawl 3"],
    ["B.O.B", "Monsters vs. Aliens", "Nickelodeon Super Brawl 3"],
    ["Sqweep", "Monsters vs. Aliens", "Nickelodeon Super Brawl 3"],
    ["Gold Ranger", "Power Rangers", "Nickelodeon Super Brawl 3"],
    ["Xandred", "Power Rangers", "Nickelodeon Super Brawl 3"],
    ["Red Ranger", "Power Rangers", "Nickelodeon Super Brawl 4", "Nickelodeon Super Brawl World"],
    ["Pink Ranger", "Power Rangers", "Nickelodeon Super Brawl 4", "Nickelodeon Super Brawl World"],
    ["Megazord", "Power Rangers", "Nickelodeon Super Brawl World"],
    ["Dragonzord", "Power Rangers", "Nickelodeon Super Brawl World"],
    ["Rabbid", "Rabbids", "Nickelodeon Super Brawl 3", "Mario + Rabbids", "Nickelodeon Super Brawl World"],
    ["Henry", "Henry Danger", "Nickelodeon Super Brawl 4", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe"],
    ["Captain Man", "Henry Danger", "Nickelodeon Super Brawl World"],
    ["Sky Whale", "Game Shakers", "Nickelodeon Super Brawl 4", "Nickelodeon Super Brawl World"],
    ["Octopie", "Game Shakers", "Nickelodeon Super Brawl World"],
    ["Harvey Beaks", "Harvey Beaks", "Nickelodeon Super Brawl 4"],
    ["Goat", "Pig Goat Banana Cricket", "Nickelodeon Super Brawl 4"],
    ["Banana", "Pig Goat Banana Cricket", "Nickelodeon Super Brawl 4"],
    ["Lincoln", "The Loud House", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Luan", "The Loud House", "Nickelodeon Super Brawl World"],
    ["Clyde", "The Loud House", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe"],
    ["Lisa", "The Loud House", "Nickelodeon Super Brawl World"],
    ["Luna", "The Loud House", "Nickelodeon Super Brawl Universe"],
    ["Lucy", "The Loud House", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Lynn", "The Loud House", "Nickelodeon All-Star Brawl"],
    ["Lola", "The Loud House", "Nickelodeon All-Star Brawl"],
    ["Lily", "The Loud House", "Nickelodeon All-Star Brawl"],
    ["Zim", "Invader Zim", "Nickelodeon Super Brawl World", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["GIR", "Invader Zim", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl 2"],
    ["GIR", "Minimoose", "Nickelodeon All-Star Brawl 2"],
    ["Bunsen", "Bunsen is a Beast", "Nickelodeon Super Brawl World"],
    ["Mikey", "Bunsen is a Beast", "Nickelodeon Super Brawl World"],
    ["Olly", "Welcome to the Wayne", "Nickelodeon Super Brawl World"],
    ["Ansi", "Welcome to the Wayne", "Nickelodeon Super Brawl World"],
    ["Saraline", "Welcome to the Wayne", "Nickelodeon Super Brawl World"],
    ["Phoebe", "The Thundermans", "Nickelodeon Super Brawl World"],
    ["Max", "The Thundermans", "Nickelodeon Super Brawl World"],
    ["Alvin", "Alvin and the Chipmunks", "Nickelodeon Super Brawl World"],
    ["Brittany", "Alvin and the Chipmunks", "Nickelodeon Super Brawl World"],
    ["CatDog", "CatDog", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl"],
    ["Tommy", "Rugrats", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl 2"],
    ["Angelica", "Rugrats", "Nickelodeon Super Brawl Universe"],
    ["Reptar", "Rugrats", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Arnold", "Hey Arnold", "Nickelodeon Super Brawl Universe"],
    ["Abner", "Hey Arnold", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl 2"],
    ["Helga", "Hey Arnold", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Phoebe", "Hey Arnold", "Nickelodeon All-Star Brawl 2"],
    ["Heffer", "Rocko's Modern Life", "Nickelodeon Super Brawl Universe"],
    ["Shredder", "Teenage Muntant Ninja Turtles", "Nickelodeon Super Brawl 3"],
    ["Rocko", "Rocko's Modern Life", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Spunky", "Rocko's Modern Life", "Nickelodeon All-Star Brawl 2"],
    ["Jenny", "My Life as a Teenage Robot", "Nickelodeon Super Brawl Universe", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Ren", "The Ren & Stimpy Show", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Stimpy", "The Ren & Stimpy Show", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Powdered Toast Man", "The Ren & Stimpy Show", "Nickelodeon All-Star Brawl"],
    ["Oblina", "Real Monsters", "Nickelodeon All-Star Brawl"],
    ["Nigel", "The Wild Thornberrys", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
    ["Garfield", "Garfield", "Nickelodeon All-Star Brawl", "Nickelodeon All-Star Brawl 2"],
]

def add_characters():
    with open("character.json", "r") as f:
        char_json = json.load(f) #type: list[dict]
    for i in new_characters:
            if i[0] in [j["name"] for j in char_json if j["name"]==i[0] and j["origin"] == i[1]]:
                 print(i[0], "from", i[1], "is already in, adding new groups")
                 new_dict = char_json.pop(char_json.index([j for j in char_json if j["name"]==i[0] and j["origin"] == i[1]][0]))
                 new_groups = new_dict["groups"] + i[1:]
                 new_groups = list(set(new_groups))
                 new_dict["groups"] = new_groups
                 char_json.append(new_dict)
            else:
                new_dict = {"name": i[0], "origin": i[1], "groups": i[1:]}
                char_json.append(new_dict)
    with open("character.json", "w") as f:
        char_json.sort(key = lambda x: x["origin"]+x["name"])
        json.dump(char_json, f, indent=4)
    print("charcters added")
def characters():
    with open("character.json", "r") as f:
        return json.load(f)

